#!/usr/bin/env python3
"""
burnout.py — Burnout Guard engine (v3.2: + transcript signal, records, CLI graph).

WHAT IT MEASURES (and deliberately doesn't)
  Burnout Guard measures HUMAN ATTENTION TIME, not tokens. Tokens measure Claude's
  spend; a two-million-token agentic run while you make coffee is not strain. Four
  hours of you typing at 1am is. So the behavioural signal is built from heartbeats:
  every prompt you send records a beat; beats <15 min apart stitch into continuous
  work blocks; blocks yield daily active hours, longest-stretch intensity, late-night
  work, and grind streaks. Self-report still leads (60%).

  v3.2 adds a SECOND beat source: Claude Code transcripts at ~/.claude/projects/.
  Each user prompt in those JSONL files is a beat. Transcripts give us cross-project
  visibility, retroactive backfill (no hook needed for history), and survive when the
  hook isn't installed. They're best-effort and merge into the same block-stitching
  pipeline; if the directory is missing or unreadable we silently fall back to
  heartbeats. claude.ai still relies on `log-session` + check-ins.

THE SIX LEVELS
  L0 Flow 0-24 | L1 Watch 25-39 | L2 Friction 40-54 | L3 Throttle 55-64
  L4 Lockout 65-84 (cooldown 12-36h, one override) | L5 Hard Lockout 85-100
  (cooldown 36-72h, no override, exit needs a recovery plan)

CLAUDE CODE INTEGRATION (real enforcement + console alerts)
  `burnout.py hook install` wires this engine into ~/.claude/settings.json:
    - UserPromptSubmit -> `heartbeat --hook`: records the beat, then
        * L4/L5: returns {"decision":"block","reason":...} — the prompt is REFUSED
          at the platform level before Claude ever sees it.
        * L3: returns a systemMessage throttle reminder (rate-limited).
        * Long stretches (90/150 min), heavy days (4h+), late-night starts:
          non-blocking systemMessage console alerts (rate-limited).
    - SessionStart -> status summary injected as context so Claude knows the level.
    - Stop -> silent heartbeat so blocks reflect full turns.

Subcommands:
  status | log-session | checkin | defer | parked | cooldown start/clear |
  override | history | report | heartbeat [--hook] [--event NAME] |
  hook install|uninstall|status

State: ~/.burnout-guard/state.json (override with BURNOUT_GUARD_HOME).
Exit codes: 0 work may proceed (L0-L2), 5 THROTTLED (L3), 10 LOCKED (L4/L5), 2 usage.
`heartbeat --hook` ALWAYS exits 0 (hook JSON carries the decision) and must never
crash a prompt.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

# ---------------------------------------------------------------- constants

HOME = Path(os.environ.get("BURNOUT_GUARD_HOME", Path.home() / ".burnout-guard"))
STATE_FILE = HOME / "state.json"
CLAUDE_SETTINGS = Path(os.environ.get("CLAUDE_SETTINGS_PATH",
                                      Path.home() / ".claude" / "settings.json"))
TRANSCRIPTS_ROOT = Path(os.environ.get("CLAUDE_PROJECTS_PATH",
                                       Path.home() / ".claude" / "projects"))
# Optional second platform: Pi coding agent session transcripts. Mirrors the Claude
# reader and is INERT unless this directory exists (so Claude-only users are unaffected).
# Override with PI_SESSIONS_PATH. See integrations/pi/ for the Pi skill + extension.
PI_SESSIONS_ROOT = Path(os.environ.get("PI_SESSIONS_PATH",
                                       Path.home() / ".pi" / "agent" / "sessions"))
TRANSCRIPT_LOOKBACK_DAYS = 30      # cap: scan files modified within this window
TRANSCRIPT_MAX_FILES = 500         # cap: refuse to scan obscene transcript counts
# Leading wrappers that mark an auto-injected Pi "user" message (skill blocks, generated
# templates) rather than a genuine human prompt. Kept narrow on purpose.
PI_INJECTION_PREFIXES = ("<skill ", "<skill>", "<!-- GENERATED BY")

LEVELS = [
    (0, "Flow",          0,  24),
    (1, "Watch",        25,  39),
    (2, "Friction",     40,  54),
    (3, "Throttle",     55,  64),
    (4, "Lockout",      65,  84),
    (5, "Hard Lockout", 85, 100),
]

LEVEL_INSTRUCTIONS = {
    0: "Normal operation.",
    1: "Normal operation; surface the index and level once at session start.",
    2: "Work proceeds. Name the score's main driver, suggest ONE adjustment, invite a "
       "check-in if basis is behaviour-only. Max one nudge per session.",
    3: "THROTTLED — single-task mode. One task only; defer the rest (`defer --task`). "
       "Suggest a ~45-min time-box. Decline new projects until the level drops.",
    4: "LOCKED — decline all task work. Permitted: conversation, status/history/report, "
       "deferring tasks, exit ritual (if timer elapsed), ONE logged override.",
    5: "HARD LOCKOUT — decline all task work; override DISABLED. Exit needs timer + "
       "check-in + written recovery plan. Crisis/safety dissolves all of this.",
}

# Index thresholds & enforcement
EXIT_INDEX_MAX = 54
RECOVERY_PLAN_MIN_CHARS = 30
OVERRIDE_PENALTY = 8
LATE_NIGHT_START, LATE_NIGHT_END = 23, 5
SELF_REPORT_WEIGHT, BEHAVIOUR_WEIGHT = 0.6, 0.4
SEVERE_SELF_REPORT_FLOOR = 0.85

# Attention-time model
BLOCK_GAP_MIN = 15            # beats closer than this stitch into one block
LONG_BLOCK_1_MIN = 90         # first "take a break" console alert
LONG_BLOCK_2_MIN = 150        # stronger alert
HEAVY_DAY_HOURS = 4           # daily active-hours alert
ALERT_REPEAT_MIN = 45         # min minutes between repeats of the same alert
THROTTLE_REMINDER_MIN = 30    # throttle systemMessage cadence

# Behaviour score weights (trailing 7 days)
W_VOLUME, W_NIGHT, W_STREAK, W_INTENSITY = 0.30, 0.25, 0.20, 0.25

# ---------------------------------------------------------------- state io

def now() -> datetime:
    return datetime.now(timezone.utc)

def iso(dt: datetime) -> str:
    return dt.isoformat(timespec="seconds")

def parse(ts: str) -> datetime:
    return datetime.fromisoformat(ts)

def default_state() -> dict:
    return {
        "version": 4,
        "config": {"tone": "supportive"},
        "created_at": iso(now()),
        "blocks": [],          # [{start, end, beats, late_night}] continuous work blocks
        "sessions": [],        # legacy/manual log-session entries (still honoured)
        "checkins": [],
        "cooldown": None,
        "parking_lot": [],
        "override_penalty": 0,
        "last_alerts": {},     # {alert_key: iso_ts} rate limiting
        "events": [],
        "records": {},         # all-time bests: longest sprint, longest streak
    }

def load_state() -> dict:
    if not STATE_FILE.exists():
        return default_state()
    try:
        state = json.loads(STATE_FILE.read_text())
    except json.JSONDecodeError:
        STATE_FILE.rename(STATE_FILE.with_suffix(".corrupt.json"))
        return default_state()
    v = state.get("version", 1)
    if v < 2:
        state.setdefault("parking_lot", [])
        if state.get("cooldown"):
            state["cooldown"].setdefault("trigger_level", 4)
            state["cooldown"].setdefault("recovery_plan", None)
    if v < 3:
        state.setdefault("blocks", [])
        state.setdefault("last_alerts", {})
    if v < 4:
        state.setdefault("records", {})
    state.setdefault("config", {"tone": "supportive"})
    state["version"] = 4
    return state

def save_state(state: dict) -> None:
    HOME.mkdir(parents=True, exist_ok=True)
    tmp = STATE_FILE.with_suffix(".tmp")
    tmp.write_text(json.dumps(state, indent=2))
    tmp.replace(STATE_FILE)

def audit(state: dict, event_type: str, detail: str) -> None:
    state["events"].append({"ts": iso(now()), "type": event_type, "detail": detail})
    state["events"] = state["events"][-500:]

# ---------------------------------------------------------------- attention

def is_late(dt_local: datetime) -> bool:
    return dt_local.hour >= LATE_NIGHT_START or dt_local.hour < LATE_NIGHT_END

def record_beat(state: dict) -> dict:
    """Stitch this moment into the current continuous block. Returns the live block."""
    t = now()
    blocks = state["blocks"]
    if blocks and (t - parse(blocks[-1]["end"])) <= timedelta(minutes=BLOCK_GAP_MIN):
        b = blocks[-1]
        b["end"] = iso(t)
        b["beats"] = b.get("beats", 1) + 1
        b["late_night"] = b.get("late_night") or is_late(datetime.now())
    else:
        b = {"start": iso(t), "end": iso(t), "beats": 1,
             "late_night": is_late(datetime.now())}
        blocks.append(b)
    state["blocks"] = blocks[-1000:]
    return b

def block_minutes(b: dict) -> float:
    return (parse(b["end"]) - parse(b["start"])).total_seconds() / 60

# ---------------------------------------------------------------- transcripts

def parse_iso_z(ts: str) -> datetime | None:
    """Parse Claude Code transcript timestamps. Tolerates trailing Z (3.10-safe)."""
    if not isinstance(ts, str):
        return None
    try:
        if ts.endswith("Z"):
            ts = ts[:-1] + "+00:00"
        return datetime.fromisoformat(ts)
    except Exception:
        return None

def transcript_beats(cutoff: datetime) -> list[datetime]:
    """Read ~/.claude/projects/**/*.jsonl and return user-prompt timestamps >= cutoff.

    Best-effort: returns [] on any error. Skips tool-result events (those have a list
    `content`); only counts genuine user prompts. Honors lookback + file caps so a
    user with hundreds of projects doesn't pay an O(N) tax on every status call."""
    beats: list[datetime] = []
    if not TRANSCRIPTS_ROOT.exists() or not TRANSCRIPTS_ROOT.is_dir():
        return beats
    file_floor = (now() - timedelta(days=TRANSCRIPT_LOOKBACK_DAYS)).timestamp()
    files: list[Path] = []
    try:
        for proj in TRANSCRIPTS_ROOT.iterdir():
            if not proj.is_dir():
                continue
            try:
                for jsonl in proj.glob("*.jsonl"):
                    try:
                        if jsonl.stat().st_mtime >= file_floor:
                            files.append(jsonl)
                    except OSError:
                        continue
            except OSError:
                continue
    except OSError:
        return beats
    if len(files) > TRANSCRIPT_MAX_FILES:
        files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        files = files[:TRANSCRIPT_MAX_FILES]

    for jsonl in files:
        try:
            with jsonl.open("r", encoding="utf-8", errors="replace") as f:
                for line in f:
                    if '"type":"user"' not in line and '"type": "user"' not in line:
                        continue
                    try:
                        ev = json.loads(line)
                    except Exception:
                        continue
                    if ev.get("type") != "user":
                        continue
                    msg = ev.get("message") or {}
                    # Tool-result envelopes carry a list content; real prompts are str.
                    if not isinstance(msg.get("content"), str):
                        continue
                    dt = parse_iso_z(ev.get("timestamp", ""))
                    if dt is None or dt < cutoff:
                        continue
                    beats.append(dt)
        except (OSError, IOError):
            continue
    beats.sort()
    return beats

def pi_session_beats(cutoff: datetime) -> list[datetime]:
    """Read Pi coding-agent sessions and return human-prompt timestamps >= cutoff.

    Mirror of transcript_beats() for the Pi platform. Pi stores sessions at
    ~/.pi/agent/sessions/--<path>--/*.jsonl. Each line is a typed entry; genuine human
    prompts are {"type":"message","message":{"role":"user",...}}. Unlike Claude, Pi
    wraps content as a list of blocks, and auto-injects skill/template blocks as "user"
    messages too — so we count text-bearing user messages whose first text block is NOT
    an injection wrapper. Best-effort: returns [] on any error, honours the same
    lookback + file caps, and is a complete no-op when the directory is absent."""
    beats: list[datetime] = []
    if not PI_SESSIONS_ROOT.exists() or not PI_SESSIONS_ROOT.is_dir():
        return beats
    file_floor = (now() - timedelta(days=TRANSCRIPT_LOOKBACK_DAYS)).timestamp()
    files: list[Path] = []
    try:
        for proj in PI_SESSIONS_ROOT.iterdir():
            if not proj.is_dir():
                continue
            try:
                for jsonl in proj.glob("*.jsonl"):
                    try:
                        if jsonl.stat().st_mtime >= file_floor:
                            files.append(jsonl)
                    except OSError:
                        continue
            except OSError:
                continue
    except OSError:
        return beats
    if len(files) > TRANSCRIPT_MAX_FILES:
        files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        files = files[:TRANSCRIPT_MAX_FILES]

    for jsonl in files:
        try:
            with jsonl.open("r", encoding="utf-8", errors="replace") as f:
                for line in f:
                    if '"role":"user"' not in line and '"role": "user"' not in line:
                        continue
                    try:
                        ev = json.loads(line)
                    except Exception:
                        continue
                    if ev.get("type") != "message":
                        continue
                    msg_obj = ev.get("message") or {}
                    if msg_obj.get("role") != "user":
                        continue
                    # Extension/skill-injected messages carry a source; skip them.
                    if ev.get("source") or msg_obj.get("source"):
                        continue
                    content = msg_obj.get("content")
                    text = ""
                    if isinstance(content, str):
                        text = content
                    elif isinstance(content, list):
                        for blk in content:
                            if isinstance(blk, dict) and blk.get("type") == "text":
                                text = blk.get("text") or ""
                                break
                        else:
                            # No text block (e.g. image-only paste) still counts as a beat.
                            text = ""
                    stripped = text.lstrip()
                    if stripped.startswith(PI_INJECTION_PREFIXES):
                        continue
                    dt = parse_iso_z(ev.get("timestamp", ""))
                    if dt is None or dt < cutoff:
                        continue
                    beats.append(dt)
        except (OSError, IOError):
            continue
    beats.sort()
    return beats

def stitch_intervals(items: list[tuple[datetime, datetime, int, bool]]) -> list[dict]:
    """Merge (start, end, beats, late) tuples into blocks using BLOCK_GAP_MIN."""
    items = sorted(items)
    merged: list[list] = []
    gap = timedelta(minutes=BLOCK_GAP_MIN)
    for s, e, beats, late in items:
        if merged and s - merged[-1][1] <= gap:
            merged[-1][1] = max(merged[-1][1], e)
            merged[-1][2] += beats
            merged[-1][3] = merged[-1][3] or late
        else:
            merged.append([s, e, beats, late])
    return [{"start": iso(s), "end": iso(e), "beats": b, "late_night": l}
            for s, e, b, l in merged]

def unified_blocks(state: dict, days: int) -> list[dict]:
    """State blocks + transcript-derived beats, merged into a single timeline."""
    cutoff = now() - timedelta(days=days)
    items: list[tuple[datetime, datetime, int, bool]] = []
    for b in state.get("blocks", []):
        s, e = parse(b["start"]), parse(b["end"])
        if e < cutoff:
            continue
        items.append((s, e, int(b.get("beats", 1)), bool(b.get("late_night", False))))
    for t in transcript_beats(cutoff):
        items.append((t, t, 1, is_late(t.astimezone())))
    for t in pi_session_beats(cutoff):
        items.append((t, t, 1, is_late(t.astimezone())))
    return stitch_intervals(items)

# ---------------------------------------------------------------- records

def update_records(state: dict, blocks: list[dict]) -> None:
    """Track all-time longest sprint and longest active-day streak (idempotent)."""
    rec = state.setdefault("records", {})
    if blocks:
        longest = max(blocks, key=block_minutes)
        cur = round(block_minutes(longest), 1)
        if cur > rec.get("longest_block_min_alltime", 0):
            rec["longest_block_min_alltime"] = cur
            rec["longest_block_at"] = longest["end"]
    days_active = {parse(b["start"]).date() for b in blocks}
    streak, d = 0, now().date()
    while d in days_active:
        streak += 1
        d -= timedelta(days=1)
    if streak > rec.get("longest_streak_days_alltime", 0):
        rec["longest_streak_days_alltime"] = streak
        rec["longest_streak_at"] = iso(now())
    rec["current_streak_days"] = streak

# ---------------------------------------------------------------- behaviour

def behaviour_score(state: dict) -> dict:
    """0-100 plus components, from merged blocks (+legacy sessions) over trailing 7 days.

    Sources merged: state['blocks'] (heartbeat-stitched, real-time) + Claude Code
    transcript prompts (cross-project, retroactive). Legacy `sessions` are still
    honoured as 30-min day credits. Records (longest-ever sprint, streak) are updated
    here so every score computation keeps them current."""
    cutoff = now() - timedelta(days=7)
    blocks = unified_blocks(state, days=7)
    sessions = [s for s in state["sessions"] if parse(s["ts"]) >= cutoff]
    update_records(state, unified_blocks(state, days=TRANSCRIPT_LOOKBACK_DAYS))

    daily_min: dict = {}
    for b in blocks:
        daily_min[parse(b["start"]).date()] = \
            daily_min.get(parse(b["start"]).date(), 0) + block_minutes(b)
    for s in sessions:                      # manual logs count as 30-min credits
        daily_min[parse(s["ts"]).date()] = daily_min.get(parse(s["ts"]).date(), 0) + 30

    avg_hours = (sum(daily_min.values()) / 60) / 7 if daily_min else 0
    longest = max((block_minutes(b) for b in blocks), default=0)
    late_n = sum(1 for b in blocks if b.get("late_night")) + \
             sum(1 for s in sessions if s.get("late_night"))

    days_active = set(daily_min)
    streak, d = 0, now().date()
    while d in days_active:
        streak += 1
        d -= timedelta(days=1)

    def clamp01(x): return max(0.0, min(1.0, x))
    volume = clamp01((avg_hours - 2) / 6) * 100          # 2h/day -> 0, 8h/day -> 100
    intensity = clamp01((longest - 60) / 180) * 100      # 1h block -> 0, 4h -> 100
    night = clamp01(late_n / 5) * 100                    # 5 late blocks/wk -> 100
    grind = clamp01((streak - 4) / 6) * 100              # 5-day streak counts, 10 max

    score = W_VOLUME * volume + W_NIGHT * night + W_STREAK * grind + W_INTENSITY * intensity
    return {"score": round(min(100, score), 1),
            "avg_hours_per_day": round(avg_hours, 2),
            "longest_block_min": round(longest),
            "late_night_blocks_7d": late_n,
            "streak_days": streak}

# ---------------------------------------------------------------- scoring

def clamp(v, lo, hi):
    return max(lo, min(hi, v))

def self_report_score(state: dict) -> float | None:
    if not state["checkins"]:
        return None
    last = state["checkins"][-1]
    if now() - parse(last["ts"]) > timedelta(hours=72):
        return None
    raw = ((last["exhaustion"] - 1) * 1.25 + (last["detachment"] - 1) * 1.25 +
           (5 - last["efficacy"]) * 1.0 + (5 - last["sleep"]) * 0.75 +
           (last["pressure"] - 1) * 0.75)
    return clamp(raw * 5.0, 0, 100)

def level_for(index: float) -> tuple[int, str]:
    for lvl, name, lo, hi in reversed(LEVELS):
        if index >= lo:
            return lvl, name
    return 0, "Flow"

def compute_index(state: dict) -> dict:
    sr = self_report_score(state)
    bh = behaviour_score(state)
    if sr is None:
        index = clamp(bh["score"], 0, 64)   # behaviour alone can throttle, never lock
        basis = "behaviour-only (no check-in in 72h; capped at L3 — invite a check-in)"
    else:
        index = SELF_REPORT_WEIGHT * sr + BEHAVIOUR_WEIGHT * bh["score"]
        index = max(index, sr * SEVERE_SELF_REPORT_FLOOR)
        basis = "blended (60% self-report, 40% behaviour; severe self-report floor)"
    index = clamp(index + state.get("override_penalty", 0), 0, 100)
    lvl, name = level_for(index)
    return {"index": round(index, 1), "level": lvl, "level_name": name,
            "self_report": None if sr is None else round(sr, 1),
            "behaviour": bh["score"], "behaviour_detail": bh,
            "basis": basis, "override_penalty": state.get("override_penalty", 0)}

def cooldown_hours_for(index: float, level: int) -> int:
    if level >= 5:
        return int(round(36 + clamp((index - 85) / 15, 0, 1) * 36))
    return int(round(12 + clamp((index - 65) / 19, 0, 1) * 24))

# ---------------------------------------------------------------- cooldown

def start_cooldown(state: dict, index: float, level: int, reason: str) -> dict:
    hours = cooldown_hours_for(index, level)
    state["cooldown"] = {"started_at": iso(now()),
                         "ends_at": iso(now() + timedelta(hours=hours)),
                         "trigger_index": index, "trigger_level": level,
                         "reason": reason, "overrides": [], "recovery_plan": None}
    audit(state, "cooldown_start", f"L{level} index={index} hours={hours} reason={reason}")
    return state["cooldown"]

def maybe_escalate(state: dict, score: dict, source: str) -> None:
    lvl, idx = score["level"], score["index"]
    cd = state.get("cooldown")
    if lvl >= 4 and not cd:
        start_cooldown(state, idx, lvl, f"auto: L{lvl} on {source}")
    elif cd and lvl == 5 and cd.get("trigger_level", 4) < 5:
        start_cooldown(state, idx, 5, f"escalation: L4 -> L5 on {source}")

def cooldown_status(state: dict) -> dict:
    cd = state.get("cooldown")
    if not cd:
        return {"locked": False}
    remaining = parse(cd["ends_at"]) - now()
    timer_elapsed = remaining.total_seconds() <= 0
    lvl = cd.get("trigger_level", 4)
    return {"locked": True, "lock_level": lvl,
            "started_at": cd["started_at"], "ends_at": cd["ends_at"],
            "timer_elapsed": timer_elapsed,
            "remaining_human": "0h 0m" if timer_elapsed else
                f"{int(remaining.total_seconds() // 3600)}h {int(remaining.total_seconds() % 3600 // 60)}m",
            "trigger_index": cd["trigger_index"], "reason": cd["reason"],
            "override_available": lvl < 5 and len(cd.get("overrides", [])) == 0,
            "overrides_used": len(cd.get("overrides", [])),
            "exit_requires": f"timer elapsed AND fresh check-in (2h) with index <= {EXIT_INDEX_MAX}"
                             + (" AND a written recovery plan (--plan)" if lvl >= 5 else "")}

# ---------------------------------------------------------------- alerts

def alert_due(state: dict, key: str, cooldown_min: int = ALERT_REPEAT_MIN) -> bool:
    last = state["last_alerts"].get(key)
    if last and now() - parse(last) < timedelta(minutes=cooldown_min):
        return False
    state["last_alerts"][key] = iso(now())
    return True

PASS_PREFIXES = ("bg:", "burnout:")   # deliberate-act prefix: always passes the hook

def tone_of(state: dict) -> str:
    return state.get("config", {}).get("tone", "supportive")

# Two voices, one engine. Sarcastic mode is opt-in (`burnout.py tone sarcastic`)
# and deliberately softens at L5 and never touches crisis territory — wit about
# the situation, never about the person's feelings.
MSG = {
    "block90": {
        "supportive": "🧯 {mins} minutes continuous — good moment for a short break.",
        "sarcastic":  "🧯 {mins} minutes straight. The bug will still be there after "
                      "you blink. Wild concept, I know: a break.",
    },
    "block150": {
        "supportive": "🧯 You've been at this {h}h {m}m without a real gap. Strong "
                      "nudge: stand up, water, 10 minutes away. The code will keep.",
        "sarcastic":  "🧯 {h}h {m}m without a gap. At this point the chair legally "
                      "owns you. Stand up — give gravity a win.",
    },
    "heavyday": {
        "supportive": "🧯 {hours}h of focused Claude work today. Worth deciding now "
                      "when today ends.",
        "sarcastic":  "🧯 {hours}h of focused work today. Bold strategy. Have you "
                      "considered scheduling the part where you stop?",
    },
    "latenight": {
        "supportive": "🧯 Late-night session logged. These weigh heavily in your "
                      "burnout index — if this becomes a pattern, the level will climb.",
        "sarcastic":  "🧯 Ah, the late-night session — famously when humanity's best "
                      "decisions get made. Noted on your permanent record "
                      "(the burnout index).",
    },
    "throttle": {
        "supportive": "🧯 Burnout Guard: index {index} — L3 Throttle. Single-task "
                      "mode: one thing at a time, ~45-min time-box; Claude will park "
                      "the rest.",
        "sarcastic":  "🧯 Index {index} — L3 Throttle. One task. Singular. I know, "
                      "devastating. Everything else goes to the parking lot, where "
                      "ideas go to survive you.",
    },
    "lock": {
        "supportive": "🧯 Burnout Guard — L{lvl} {name} active. {remaining} remaining "
                      "(triggered at index {idx}). Task work is paused. You can still "
                      "chat, check status, or park tasks{override}. Start any message "
                      "with `bg:` to talk to Claude — that channel is ALWAYS open "
                      "(venting, status, parking tasks, the exit ritual, and anything "
                      "urgent or personal).",
        "sarcastic":  "🧯 L{lvl} {name}: {remaining} remaining. You did technically do "
                      "this to yourself (index {idx}){override}. Complaints department "
                      "is open — start any message with `bg:` and Claude will listen "
                      "to all of them. That channel always works, including for "
                      "anything actually serious.",
    },
    "timer_done": {
        "supportive": "🧯 Burnout Guard — L{lvl} cooldown timer has elapsed. Exit "
                      "ritual required: a fresh check-in scoring <= {exitmax}{plan}. "
                      "Start your message with `bg:` to run it, e.g. `bg: let's do "
                      "the exit check-in`.",
        "sarcastic":  "🧯 Timer's done — congratulations on surviving rest. One "
                      "formality left: an exit check-in scoring <= {exitmax}{plan}. "
                      "Type `bg: let's do the exit check-in` and prove it.",
    },
    "bg_open": {
        "supportive": "🧯 bg: channel open — L{lvl} protocol still applies "
                      "(conversation, status, parking, exit ritual, emergencies; "
                      "no task work).",
        "sarcastic":  "🧯 bg: channel open. Talk away — but the workbench stays "
                      "locked (L{lvl}), and no, rephrasing the task as a fun "
                      "hypothetical doesn't count.",
    },
}

def msg(state: dict, key: str, **kw) -> str:
    t = tone_of(state)
    # L5 always softens back to supportive phrasing for lock/timer messages —
    # sarcasm has a floor.
    if key in ("lock", "timer_done") and kw.get("lvl", 0) >= 5:
        t = "supportive"
    return MSG[key][t].format(**kw)

def build_console_alerts(state: dict, block: dict, score: dict, cd: dict,
                         prompt: str = "") -> dict:
    """Returns hook-output JSON: a block decision, a systemMessage alert, or {}."""
    # Deliberate-act passthrough: conversation, exit ritual, parking, emergencies.
    # Claude still applies the level protocol (no task work at L4/L5) — this opens
    # the conversational channel, not the workbench.
    if cd["locked"] and prompt.strip().lower().startswith(PASS_PREFIXES):
        lvl = cd["lock_level"]
        return {"systemMessage": msg(state, "bg_open", lvl=lvl),
                "hookSpecificOutput": {"hookEventName": "UserPromptSubmit",
                    "additionalContext": f"Burnout Guard: L{lvl} lockout active; user "
                        "opened the bg: channel. Follow the lockout protocol — "
                        "conversation/status/parking/exit ritual yes, task work no. "
                        "Crisis or distress dissolves all lockout framing."}}
    # 0) Override grace window: enforcement pauses for 60 min after an L4 override.
    grace = state["last_alerts"].get("override_grace_until")
    if cd["locked"] and grace and now() < parse(grace):
        return {"systemMessage": "🧯 Override grace active — lockout enforcement "
                                 "resumes when the 60-minute window closes."}

    # 1) Locked: hard-block the prompt at the platform level.
    if cd["locked"]:
        lock_lvl = cd["lock_level"]
        if cd["timer_elapsed"]:
            reason = msg(state, "timer_done", lvl=lock_lvl, exitmax=EXIT_INDEX_MAX,
                         plan=(" plus a short written recovery plan" if lock_lvl >= 5 else ""))
        else:
            override_txt = (". One logged override is available for genuine emergencies"
                            if cd["override_available"] else
                            "; no override at this level" if lock_lvl >= 5 else
                            "; the override has been used")
            reason = msg(state, "lock", lvl=lock_lvl,
                         name="Hard Lockout" if lock_lvl >= 5 else "Lockout",
                         remaining=cd["remaining_human"], idx=cd["trigger_index"],
                         override=override_txt)
        return {"decision": "block", "reason": reason}

    msgs = []
    mins = block_minutes(block)
    bd = score["behaviour_detail"]

    # 2) Throttle reminder (rate-limited).
    if score["level"] == 3 and alert_due(state, "throttle", THROTTLE_REMINDER_MIN):
        msgs.append(msg(state, "throttle", index=score["index"]))

    # 3) Continuous-stretch alerts.
    if mins >= LONG_BLOCK_2_MIN and alert_due(state, "block150"):
        msgs.append(msg(state, "block150", h=int(mins // 60), m=int(mins % 60)))
    elif mins >= LONG_BLOCK_1_MIN and alert_due(state, "block90"):
        msgs.append(msg(state, "block90", mins=int(mins)))

    # 4) Heavy-day alert.
    today_min = sum(block_minutes(b) for b in state["blocks"]
                    if parse(b["start"]).date() == now().date())
    if today_min >= HEAVY_DAY_HOURS * 60 and alert_due(state, "heavyday", 120):
        msgs.append(msg(state, "heavyday", hours=f"{today_min / 60:.1f}"))

    # 5) Late-night start.
    if is_late(datetime.now()) and alert_due(state, "latenight", 120):
        msgs.append(msg(state, "latenight"))

    if msgs:
        return {"systemMessage": " ".join(msgs)}
    return {}

# ---------------------------------------------------------------- commands

def cmd_heartbeat(args):
    """Called by Claude Code hooks on every prompt/turn. Must never crash a prompt."""
    try:
        try:
            hook_input = json.loads(sys.stdin.read()) if not sys.stdin.isatty() else {}
        except Exception:
            hook_input = {}
        state = load_state()
        block = record_beat(state)
        score = compute_index(state)
        maybe_escalate(state, score, "heartbeat")
        cd = cooldown_status(state)

        if args.event == "session-start":
            ctx = (f"Burnout Guard status: index {score['index']} — "
                   f"L{score['level']} {score['level_name']}. "
                   f"{LEVEL_INSTRUCTIONS[max(score['level'], cd['lock_level'] if cd['locked'] else 0)]}")
            out = {"hookSpecificOutput": {"hookEventName": "SessionStart",
                                          "additionalContext": ctx}}
        elif args.event == "stop":
            out = {}                      # silent: just extends the block
        else:                             # user-prompt-submit (default)
            prompt = hook_input.get("prompt", "") if isinstance(hook_input, dict) else ""
            out = build_console_alerts(state, block, score, cd, prompt) if args.hook \
                  else {"beat": True, "score": score, "cooldown": cd}
        save_state(state)
        print(json.dumps(out))
    except Exception as e:
        # Fail open: never break the user's prompt because of us.
        print(json.dumps({}))
        print(f"burnout-guard heartbeat error: {e}", file=sys.stderr)
    sys.exit(0)

def cmd_status(args):
    state = load_state()
    score = compute_index(state)
    cd = cooldown_status(state)
    if cd["locked"]:
        effective, verdict, code = max(score["level"], cd["lock_level"], 4), "LOCKED", 10
    elif score["level"] == 3:
        effective, verdict, code = 3, "THROTTLED", 5
    else:
        effective, verdict, code = score["level"], "UNLOCKED", 0
    print(json.dumps({"score": score, "effective_level": effective,
                      "effective_level_name": dict((l, n) for l, n, *_ in LEVELS)[effective],
                      "cooldown": cd, "parking_lot_size": len(state["parking_lot"]),
                      "verdict": verdict, "tone": tone_of(state),
                      "records": state.get("records", {}),
                      "instruction": LEVEL_INSTRUCTIONS[effective]},
                     indent=2))
    sys.exit(code)

def cmd_log_session(args):
    state = load_state()
    late = is_late(datetime.now())
    state["sessions"].append({"ts": iso(now()), "late_night": late})
    state["sessions"] = state["sessions"][-1000:]
    record_beat(state)
    audit(state, "session", f"late_night={late}")
    score = compute_index(state)
    maybe_escalate(state, score, "session log")
    save_state(state)
    print(json.dumps({"logged": True, "late_night": late, "score": score,
                      "cooldown": cooldown_status(state)}, indent=2))

def cmd_checkin(args):
    state = load_state()
    for field in ("exhaustion", "detachment", "efficacy", "sleep", "pressure"):
        if not 1 <= getattr(args, field) <= 5:
            print(f"error: --{field} must be 1-5", file=sys.stderr)
            sys.exit(2)
    entry = {"ts": iso(now()), "exhaustion": args.exhaustion,
             "detachment": args.detachment, "efficacy": args.efficacy,
             "sleep": args.sleep, "pressure": args.pressure, "notes": args.notes or ""}
    state["checkins"].append(entry)
    state["checkins"] = state["checkins"][-365:]
    score = compute_index(state)
    entry["index_at_checkin"] = score["index"]
    if score["level"] <= 1:
        state["override_penalty"] = 0
        score = compute_index(state)
    audit(state, "checkin", f"index={score['index']} L{score['level']}")
    maybe_escalate(state, score, "check-in")
    save_state(state)
    print(json.dumps({"recorded": True, "score": score,
                      "cooldown": cooldown_status(state)}, indent=2))

def cmd_defer(args):
    state = load_state()
    task = (args.task or "").strip()
    if len(task) < 3:
        print("error: --task description required", file=sys.stderr)
        sys.exit(2)
    state["parking_lot"].append({"ts": iso(now()), "task": task})
    audit(state, "defer", task[:120])
    save_state(state)
    print(json.dumps({"deferred": True, "parking_lot_size": len(state["parking_lot"])},
                     indent=2))

def cmd_parked(args):
    state = load_state()
    if args.clear:
        n = len(state["parking_lot"])
        state["parking_lot"] = []
        audit(state, "parking_lot_clear", f"cleared {n}")
        save_state(state)
        print(json.dumps({"cleared": n}, indent=2))
        return
    print(json.dumps({"parking_lot": state["parking_lot"]}, indent=2))

def cmd_cooldown(args):
    state = load_state()
    if args.action == "start":
        score = compute_index(state)
        start_cooldown(state, max(score["index"], 65), max(score["level"], 4),
                       args.reason or "manual start")
        save_state(state)
        print(json.dumps({"started": True, "cooldown": cooldown_status(state)}, indent=2))
        return
    cd = cooldown_status(state)
    if not cd["locked"]:
        print(json.dumps({"cleared": False, "detail": "no active cooldown"}, indent=2))
        return
    if not cd["timer_elapsed"]:
        print(json.dumps({"cleared": False,
                          "detail": f"timer not elapsed — {cd['remaining_human']} remaining"},
                         indent=2))
        sys.exit(10)
    fresh = state["checkins"] and (now() - parse(state["checkins"][-1]["ts"]) < timedelta(hours=2))
    if not fresh:
        print(json.dumps({"cleared": False,
                          "detail": "exit check-in required (within last 2h) before clearing"},
                         indent=2))
        sys.exit(10)
    score = compute_index(state)
    if score["index"] > EXIT_INDEX_MAX:
        start_cooldown(state, score["index"], max(score["level"], 4),
                       "extension: exit check-in still too high")
        save_state(state)
        print(json.dumps({"cleared": False, "extended": True,
                          "detail": f"index {score['index']} > {EXIT_INDEX_MAX}; cooldown extended",
                          "cooldown": cooldown_status(state)}, indent=2))
        sys.exit(10)
    if cd["lock_level"] >= 5:
        plan = (args.plan or "").strip()
        if len(plan) < RECOVERY_PLAN_MIN_CHARS:
            print(json.dumps({"cleared": False,
                              "detail": f"L5 exit requires --plan >= {RECOVERY_PLAN_MIN_CHARS} chars: "
                                        "what changes this week so this doesn't recur?"},
                             indent=2))
            sys.exit(10)
        state["cooldown"]["recovery_plan"] = plan
        audit(state, "recovery_plan", plan[:200])
    audit(state, "cooldown_clear", f"exit index={score['index']}")
    state["cooldown"] = None
    save_state(state)
    out = {"cleared": True, "score": score, "parking_lot_size": len(state["parking_lot"])}
    if state["parking_lot"]:
        out["detail"] = "Parking lot has items — offer them back one at a time."
    print(json.dumps(out, indent=2))

def cmd_override(args):
    state = load_state()
    cd = state.get("cooldown")
    if not cd:
        print(json.dumps({"override": False, "detail": "no active cooldown"}, indent=2))
        return
    if cd.get("trigger_level", 4) >= 5:
        print(json.dumps({"override": False,
                          "detail": "Hard Lockout (L5): overrides are disabled by design."},
                         indent=2))
        sys.exit(10)
    if len(cd.get("overrides", [])) >= 1:
        print(json.dumps({"override": False,
                          "detail": "override already used for this cooldown"}, indent=2))
        sys.exit(10)
    if not args.reason or len(args.reason.strip()) < 15:
        print("error: --reason of at least 15 characters required (it is logged)",
              file=sys.stderr)
        sys.exit(2)
    cd["overrides"].append({"ts": iso(now()), "reason": args.reason.strip()})
    state["override_penalty"] = state.get("override_penalty", 0) + OVERRIDE_PENALTY
    # Grace window: next prompts within 60 min won't be hard-blocked by the hook.
    state["last_alerts"]["override_grace_until"] = iso(now() + timedelta(minutes=60))
    audit(state, "override", args.reason.strip())
    save_state(state)
    print(json.dumps({"override": True,
                      "detail": "One-time pass: hook enforcement pauses for 60 minutes "
                                "for THIS task, then the lockout resumes. "
                                f"+{OVERRIDE_PENALTY} penalty until next calm check-in."},
                     indent=2))

def cmd_history(args):
    state = load_state()
    print(json.dumps({"recent_checkins": state["checkins"][-args.n:],
                      "recent_blocks": state["blocks"][-args.n:],
                      "recent_events": state["events"][-args.n:],
                      "parking_lot": state["parking_lot"]}, indent=2))

SPARK_BARS = "▁▂▃▄▅▆▇█"

def sparkline(values: list[float]) -> str:
    if not values:
        return ""
    hi = max(values)
    if hi <= 0:
        return SPARK_BARS[0] * len(values)
    out = []
    for v in values:
        if v <= 0:
            out.append(" ")
        else:
            out.append(SPARK_BARS[min(len(SPARK_BARS) - 1,
                                      int(v / hi * (len(SPARK_BARS) - 1) + 0.5))])
    return "".join(out)

def daily_minutes(blocks: list[dict], days: int) -> list[tuple[str, float]]:
    """Returns [(YYYY-MM-DD, minutes)] for the last `days` days, oldest first."""
    today = now().astimezone().date()
    bucket: dict = {today - timedelta(days=i): 0.0 for i in range(days)}
    for b in blocks:
        s, e = parse(b["start"]).astimezone(), parse(b["end"]).astimezone()
        cur = s
        while cur < e:
            day_end = datetime.combine(cur.date(), datetime.min.time(),
                                       tzinfo=cur.tzinfo) + timedelta(days=1)
            chunk_end = min(day_end, e)
            mins = (chunk_end - cur).total_seconds() / 60
            if cur.date() in bucket:
                bucket[cur.date()] += mins
            cur = chunk_end
    return [(d.isoformat(), round(m, 1))
            for d, m in sorted(bucket.items())]

HEATMAP_SHADES = " ░▒▓█"

def heatmap_7x24(blocks: list[dict]) -> list[str]:
    """7×24 grid (Mon..Sun × hour-of-day) of focused minutes. Local time."""
    grid = [[0.0] * 24 for _ in range(7)]
    for b in blocks:
        s = parse(b["start"]).astimezone()
        e = parse(b["end"]).astimezone()
        cur = s.replace(minute=0, second=0, microsecond=0)
        while cur < e:
            nxt = cur + timedelta(hours=1)
            mins = (min(nxt, e) - max(cur, s)).total_seconds() / 60
            if mins > 0:
                grid[cur.weekday()][cur.hour] += mins
            cur = nxt
    flat = [v for row in grid for v in row]
    hi = max(flat) if flat else 0
    if hi <= 0:
        return ["  (no recorded activity in window)"]
    days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    header = "      " + "".join(f"{h:>3}" for h in (0, 3, 6, 9, 12, 15, 18, 21))
    lines = [header]
    for i, row in enumerate(grid):
        cells = ""
        for v in row:
            if v <= 0:
                cells += HEATMAP_SHADES[0]
            else:
                idx = min(len(HEATMAP_SHADES) - 1,
                          1 + int((v / hi) * (len(HEATMAP_SHADES) - 2) + 0.5))
                cells += HEATMAP_SHADES[idx]
        lines.append(f"  {days[i]} {cells}")
    lines.append(f"  legend: {HEATMAP_SHADES} (none → ~{int(hi)} min/cell)")
    return lines

def cmd_report(args):
    state = load_state()
    score = compute_index(state)
    cd = cooldown_status(state)
    bd = score["behaviour_detail"]
    cutoff = now() - timedelta(days=14)
    checkins = [c for c in state["checkins"] if parse(c["ts"]) >= cutoff]
    lockouts = [e for e in state["events"]
                if e["type"] == "cooldown_start" and parse(e["ts"]) >= cutoff]
    blocks_14 = unified_blocks(state, days=14)
    rec = state.get("records", {})

    daily = daily_minutes(blocks_14, 14)
    spark = sparkline([m for _, m in daily])
    peak_min = max((m for _, m in daily), default=0)

    lines = [
        "# Burnout Guard — 14-day report",
        f"\n**Current index:** {score['index']} — **L{score['level']} {score['level_name']}**",
        f"**Basis:** {score['basis']}",
        f"**Lockout:** {'ACTIVE (L' + str(cd['lock_level']) + ') until ' + cd['ends_at'] if cd['locked'] else 'none'}",
        f"\n## Attention (trailing 7 days)",
        f"- Average focused hours/day: {bd['avg_hours_per_day']}",
        f"- Longest continuous stretch: {bd['longest_block_min']} min",
        f"- Late-night blocks: {bd['late_night_blocks_7d']}",
        f"- Active-day streak: {bd['streak_days']}",
        f"- Behaviour score: {bd['score']}/100",
        f"\n## Daily focus (14d, mins/day, peak ~{int(peak_min)})",
        f"  {daily[0][0]} {spark} {daily[-1][0]}",
        f"\n## Hour-of-day × day-of-week (14d, local time)",
        *heatmap_7x24(blocks_14),
        f"\n## Records",
        f"- Longest sprint ever: {rec.get('longest_block_min_alltime', 0)} min"
        + (f" (on {rec['longest_block_at']})" if rec.get('longest_block_at') else ""),
        f"- Longest active-day streak: {rec.get('longest_streak_days_alltime', 0)} day(s)"
        + (f", current streak: {rec.get('current_streak_days', 0)}"),
        f"\n## Self-report\n- Check-ins (14d): {len(checkins)}",
    ]
    if checkins:
        last = checkins[-1]
        lines.append(f"- Latest ({last['ts']}): exhaustion {last['exhaustion']}/5, "
                     f"detachment {last['detachment']}/5, efficacy {last['efficacy']}/5, "
                     f"sleep {last['sleep']}/5, pressure {last['pressure']}/5")
    lines += [f"\n## Enforcement\n- Lockouts triggered (14d): {len(lockouts)}",
              f"- Parking lot: {len(state['parking_lot'])} item(s)",
              f"- Override penalty in effect: +{state.get('override_penalty', 0)}",
              f"\n## Audit\n- Events logged: {len(state['events'])}"]
    if len(lockouts) >= 2:
        lines.append("\n> Two or more lockouts in 14 days. The pattern, not the timer, is "
                     "the signal — consider a conversation with a GP or occupational health.")
    # Persist any updates update_records made via behaviour_score.
    save_state(state)
    print("\n".join(lines))

def cmd_tone(args):
    state = load_state()
    if args.mode == "show":
        print(json.dumps({"tone": tone_of(state)}, indent=2))
        return
    state.setdefault("config", {})["tone"] = args.mode
    audit(state, "tone", args.mode)
    save_state(state)
    samples = {k: MSG[k][args.mode if args.mode in MSG[k] else "supportive"]
               for k in ("block90", "lock")}
    print(json.dumps({"tone": args.mode,
                      "detail": "Applies to console alerts and lockout notices. "
                                "Sarcasm softens automatically at L5 and never "
                                "applies to crisis or distress — wit about the "
                                "situation, never about the person.",
                      "sample": samples}, indent=2))

# ---------------------------------------------------------------- hook mgmt

HOOK_MARKER = "burnout.py heartbeat"

def hook_entries(script: str) -> dict:
    return {
        "UserPromptSubmit": [{"hooks": [{"type": "command",
            "command": f"python3 {script} heartbeat --hook"}]}],
        "SessionStart": [{"hooks": [{"type": "command",
            "command": f"python3 {script} heartbeat --hook --event session-start"}]}],
        "Stop": [{"hooks": [{"type": "command",
            "command": f"python3 {script} heartbeat --hook --event stop"}]}],
    }

def cmd_hook(args):
    script = str(Path(__file__).resolve())
    settings_path = CLAUDE_SETTINGS
    settings = {}
    if settings_path.exists():
        try:
            settings = json.loads(settings_path.read_text())
        except json.JSONDecodeError:
            print(f"error: {settings_path} is not valid JSON — fix it first", file=sys.stderr)
            sys.exit(2)

    hooks = settings.get("hooks", {})
    installed = any(HOOK_MARKER in json.dumps(v) for v in hooks.values())

    if args.action == "status":
        print(json.dumps({"settings_path": str(settings_path),
                          "installed": installed, "script": script}, indent=2))
        return

    if args.action == "uninstall":
        for event in list(hooks):
            hooks[event] = [m for m in hooks[event]
                            if HOOK_MARKER not in json.dumps(m)]
            if not hooks[event]:
                del hooks[event]
        settings["hooks"] = hooks
        settings_path.write_text(json.dumps(settings, indent=2))
        print(json.dumps({"uninstalled": True}, indent=2))
        return

    # install
    if settings_path.exists():
        backup = settings_path.with_suffix(f".json.bak-{now().strftime('%Y%m%d%H%M%S')}")
        backup.write_text(settings_path.read_text())
    if installed:
        cmd_hook(argparse.Namespace(action="uninstall"))   # refresh paths
        settings = json.loads(settings_path.read_text()) if settings_path.exists() else {}
        hooks = settings.get("hooks", {})
    for event, matchers in hook_entries(script).items():
        hooks.setdefault(event, []).extend(matchers)
    settings["hooks"] = hooks
    settings_path.parent.mkdir(parents=True, exist_ok=True)
    settings_path.write_text(json.dumps(settings, indent=2))
    print(json.dumps({"installed": True, "settings_path": str(settings_path),
                      "events": list(hook_entries(script)),
                      "detail": "Restart Claude Code (or /hooks to verify). "
                                "Prompts now heartbeat; L4/L5 hard-block; console "
                                "alerts on long stretches, heavy days, late nights."},
                     indent=2))

# ---------------------------------------------------------------- main

def main():
    p = argparse.ArgumentParser(prog="burnout.py", description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("status").set_defaults(fn=cmd_status)
    sub.add_parser("log-session").set_defaults(fn=cmd_log_session)

    hb = sub.add_parser("heartbeat")
    hb.add_argument("--hook", action="store_true",
                    help="emit Claude Code hook JSON (block/systemMessage)")
    hb.add_argument("--event", choices=["prompt", "session-start", "stop"],
                    default="prompt")
    hb.set_defaults(fn=cmd_heartbeat)

    hk = sub.add_parser("hook")
    hk.add_argument("action", choices=["install", "uninstall", "status"])
    hk.set_defaults(fn=cmd_hook)

    ci = sub.add_parser("checkin")
    for f, h in [("exhaustion", "1=fresh 5=fumes"), ("detachment", "1=engaged 5=checked out"),
                 ("efficacy", "1=useless 5=on top of it"), ("sleep", "1=terrible 5=great"),
                 ("pressure", "1=light 5=crushing")]:
        ci.add_argument(f"--{f}", type=int, required=True, help=h)
    ci.add_argument("--notes", type=str, default="")
    ci.set_defaults(fn=cmd_checkin)

    df = sub.add_parser("defer")
    df.add_argument("--task", type=str, required=True)
    df.set_defaults(fn=cmd_defer)

    pk = sub.add_parser("parked")
    pk.add_argument("--clear", action="store_true")
    pk.set_defaults(fn=cmd_parked)

    cd = sub.add_parser("cooldown")
    cd.add_argument("action", choices=["start", "clear"])
    cd.add_argument("--reason", type=str, default="")
    cd.add_argument("--plan", type=str, default="")
    cd.set_defaults(fn=cmd_cooldown)

    ov = sub.add_parser("override")
    ov.add_argument("--reason", type=str, required=True)
    ov.set_defaults(fn=cmd_override)

    tn = sub.add_parser("tone")
    tn.add_argument("mode", choices=["supportive", "sarcastic", "show"])
    tn.set_defaults(fn=cmd_tone)

    hi = sub.add_parser("history")
    hi.add_argument("-n", type=int, default=10)
    hi.set_defaults(fn=cmd_history)

    sub.add_parser("report").set_defaults(fn=cmd_report)

    args = p.parse_args()
    args.fn(args)

if __name__ == "__main__":
    main()
