#!/usr/bin/env python3
"""
burnout.py — Burnout Guard engine (v5: sprint-aware. Multi-week strain, sprint
declaration, per-project rollup, conservative stuck detection, recovery
prescription, legacy grind-streak removed).

WHAT IT MEASURES (and deliberately doesn't)
  Burnout Guard measures HUMAN ATTENTION TIME, not tokens. Tokens measure Claude's
  spend; a two-million-token agentic run while you make coffee is not strain. Four
  hours of you typing at 1am is. So the behavioural signal is built from heartbeats:
  every prompt you send records a beat; beats <15 min apart stitch into continuous
  work blocks; blocks yield daily active hours, longest-stretch intensity, late-night
  work, and rhythm streaks. Self-report still leads (60%).

  v3.2 added a SECOND beat source: Claude Code transcripts at ~/.claude/projects/.
  Each user prompt in those JSONL files is a beat. Cross-project visibility,
  retroactive backfill, hook-independent measurement.

  v4 adds PERSONAL CALIBRATION on top:
    - Personal baseline: alert thresholds derived from your trailing 30-day p75/p90,
      clamped to absolute floors/ceilings. Marathon user gets alerts at THEIR 90th
      percentile, not at an absolute number; recovery user the same. No profiles, no
      loophole-by-preset.
    - Contracts: Beeminder-style pre-commitment. Strictening is instant; loosening
      has a 7-day cooling-off. The only configurability is a one-way ratchet toward
      protection.
    - Daily 1-item pulse (West et al.): 3-second daily check that smooths the
      self-report curve and lifts the behaviour-only L3 cap when fresh.
    - Sustainable-rhythm streak: replaces the grind-streak trophy. Counts days where
      work happened AND no block exceeded the long-block-2 threshold AND no late-
      night block fired. v4 keeps the legacy streak with a deprecation note; v5 will
      drop it.
    - Preview mode: first 7 days from install, L4/L5 blocks surface as warnings
      instead of platform-blocking, so day-one users meet the system gradually.

THE SIX LEVELS
  L0 Flow 0-24 | L1 Watch 25-39 | L2 Friction 40-54 | L3 Throttle 55-64
  L4 Lockout 65-84 (cooldown 12-36h, one override) | L5 Hard Lockout 85-100
  (cooldown 36-72h, no override, exit needs a recovery plan)

CLAUDE CODE INTEGRATION (real enforcement + console alerts)
  `burnout.py hook install` wires this engine into ~/.claude/settings.json:
    - UserPromptSubmit -> `heartbeat --hook`: records the beat, then
        * L4/L5: returns {"decision":"block","reason":...} — the prompt is REFUSED
          at the platform level before Claude ever sees it.
        * L3: returns a systemMessage throttle reminder (rate-limited).
        * Long stretches (90/150 min), heavy days (4h+), late-night starts:
          non-blocking systemMessage console alerts (rate-limited).
    - SessionStart -> status summary injected as context so Claude knows the level.
    - Stop -> silent heartbeat so blocks reflect full turns.

Subcommands:
  status | log-session | checkin | pulse N | contract set/show/clear |
  defer | parked | cooldown start/clear | override | tone | history | report |
  heartbeat [--hook] [--event NAME] | hook install|uninstall|status

State: ~/.burnout-guard/state.json (override with BURNOUT_GUARD_HOME).
Exit codes: 0 work may proceed (L0-L2), 5 THROTTLED (L3), 10 LOCKED (L4/L5), 2 usage.
`heartbeat --hook` ALWAYS exits 0 (hook JSON carries the decision) and must never
crash a prompt.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

# ---------------------------------------------------------------- constants

HOME = Path(os.environ.get("BURNOUT_GUARD_HOME", Path.home() / ".burnout-guard"))
STATE_FILE = HOME / "state.json"
CLAUDE_SETTINGS = Path(os.environ.get("CLAUDE_SETTINGS_PATH",
                                      Path.home() / ".claude" / "settings.json"))
TRANSCRIPTS_ROOT = Path(os.environ.get("CLAUDE_PROJECTS_PATH",
                                       Path.home() / ".claude" / "projects"))
# Optional second platform: Pi coding agent session transcripts. Mirrors the Claude
# reader and is INERT unless this directory exists (so Claude-only users are unaffected).
# Override with PI_SESSIONS_PATH. See integrations/pi/ for the Pi skill + extension.
PI_SESSIONS_ROOT = Path(os.environ.get("PI_SESSIONS_PATH",
                                       Path.home() / ".pi" / "agent" / "sessions"))
TRANSCRIPT_LOOKBACK_DAYS = 30      # cap: scan files modified within this window
TRANSCRIPT_MAX_FILES = 500         # cap: refuse to scan obscene transcript counts
# Leading wrappers that mark an auto-injected Pi "user" message (skill blocks, generated
# templates) rather than a genuine human prompt. Kept narrow on purpose.
PI_INJECTION_PREFIXES = ("<skill ", "<skill>", "<!-- GENERATED BY")

LEVELS = [
    (0, "Flow",          0,  24),
    (1, "Watch",        25,  39),
    (2, "Friction",     40,  54),
    (3, "Throttle",     55,  64),
    (4, "Lockout",      65,  84),
    (5, "Hard Lockout", 85, 100),
]

LEVEL_INSTRUCTIONS = {
    0: "Normal operation.",
    1: "Normal operation; surface the index and level once at session start.",
    2: "Work proceeds. Name the score's main driver, suggest ONE adjustment, invite a "
       "check-in if basis is behaviour-only. Max one nudge per session.",
    3: "THROTTLED — single-task mode. One task only; defer the rest (`defer --task`). "
       "Suggest a ~45-min time-box. Decline new projects until the level drops.",
    4: "LOCKED — decline all task work. Permitted: conversation, status/history/report, "
       "deferring tasks, exit ritual (if timer elapsed), ONE logged override.",
    5: "HARD LOCKOUT — decline all task work; override DISABLED. Exit needs timer + "
       "check-in + written recovery plan. Crisis/safety dissolves all of this.",
}

# Index thresholds & enforcement
EXIT_INDEX_MAX = 54
RECOVERY_PLAN_MIN_CHARS = 30
OVERRIDE_PENALTY = 8
LATE_NIGHT_START, LATE_NIGHT_END = 23, 5
SELF_REPORT_WEIGHT, BEHAVIOUR_WEIGHT = 0.6, 0.4
SEVERE_SELF_REPORT_FLOOR = 0.85

# Attention-time model
BLOCK_GAP_MIN = 15            # beats closer than this stitch into one block
LONG_BLOCK_1_MIN = 90         # first "take a break" console alert
LONG_BLOCK_2_MIN = 150        # stronger alert
HEAVY_DAY_HOURS = 4           # daily active-hours alert
ALERT_REPEAT_MIN = 45         # min minutes between repeats of the same alert
THROTTLE_REMINDER_MIN = 30    # throttle systemMessage cadence

# Behaviour score weights (trailing 7 days)
W_VOLUME, W_NIGHT, W_STREAK, W_INTENSITY = 0.30, 0.25, 0.20, 0.25

# Personal-baseline calibration (v4). Floors keep an inactive user from disabling
# protection ("my p90 block is 12 minutes so alert at 12 minutes" — no thanks).
# Ceilings keep a marathon baseline from removing the cap entirely.
BASELINE_LOOKBACK_DAYS = 30
BASELINE_MIN_DAYS_ACTIVE = 14
BASELINE_BOUNDS = {           # threshold_key: (floor, ceiling)
    "long_block_1_min": (60, 150),
    "long_block_2_min": (120, 300),
    "heavy_day_hours":  (3, 8),
}

# Contracts (v4) — pre-commitment; loosening has a 7-day cooling-off.
CONTRACT_LOOSEN_COOLOFF_DAYS = 7
CONTRACT_FIELDS = ("lockout_index", "stop_by_hour", "max_daily_hours")
# Defaults each contract field is compared against to decide stricter/looser.
CONTRACT_DEFAULTS = {
    "lockout_index":   65,                  # L4 boundary
    "stop_by_hour":    LATE_NIGHT_START,    # 23
    "max_daily_hours": HEAVY_DAY_HOURS,     # 4
}
# Direction of strictness: -1 means "lower is stricter", +1 "higher is stricter".
CONTRACT_STRICT_DIR = {"lockout_index": -1, "stop_by_hour": -1, "max_daily_hours": -1}

# Preview mode (v4) — first 7 days from state.created_at, L4/L5 blocks surface as
# warnings rather than platform-blocking the prompt. Solves day-one surprise without
# becoming a config knob.
PREVIEW_DAYS = 7

# Pulse (v4) — single-item daily burnout check (West et al. style).
PULSE_FRESH_HOURS = 24
PULSE_TO_INDEX = {1: 5, 2: 25, 3: 50, 4: 75, 5: 90}   # 1=fresh, 5=fumes

# Strain accumulation (v5) — Whoop-style "load - recovery" debt over 30 days.
# A day under your typical load is recovery credit; a day over is debt. The score is
# clamped against MAX_STRAIN_DEBT_HRS so a single bad week doesn't max it out, but
# three of them will.
STRAIN_LOOKBACK_DAYS = 30
MAX_STRAIN_DEBT_HRS = 30          # cumulative hours over baseline → strain 100
STRAIN_DEBT_BANDS = [             # (max_strain_value, label, instruction)
    (39,  "Light",      "Strain trajectory is healthy."),
    (59,  "Moderate",   "Strain is climbing — protect at least one recovery day this week."),
    (79,  "High",       "Heavy 30-day strain — schedule a real day off in the next 72 hours."),
    (100, "Critical",   "Sustained strain debt — back-to-back recovery days are owed and "
                        "should be taken before another sprint."),
]

# Sprint declaration (v5) — committed effort window. During: thresholds relaxed
# (you said you'd push, system stops crying wolf). After: auto post-recovery period
# with tightened thresholds and lockout floor pulled in.
SPRINT_DURING_HEAVY_DAY_MULT = 1.5     # 4h -> 6h, etc. Still clamped within bounds.
SPRINT_DURING_BLOCK_MULT     = 1.3     # 90 -> ~117 min
SPRINT_RECOVERY_RATIO        = 0.5     # post-recovery duration = sprint duration * this
SPRINT_RECOVERY_HEAVY_MULT   = 0.7
SPRINT_RECOVERY_LOCKOUT_IDX  = 60       # post-recovery lockout boundary
SPRINT_CANCEL_COOLOFF_DAYS   = 7
SPRINT_MAX_DAYS              = 21       # sanity cap on duration

# Per-project rollup (v5)
PROJECT_DEEP_WORK_MULT = 1.25         # raises long-block thresholds when active in flagged project

# Stuck-loop detection (v5, conservative)
STUCK_WINDOW_MIN     = 10             # look back this many minutes
STUCK_MIN_PROMPTS    = 4              # need at least this many similar prompts
STUCK_JACCARD_MEAN   = 0.5            # pairwise mean Jaccard threshold
STUCK_BLOCK1_FRACTION = 0.6            # nudge fires at this fraction of long_block_1
STUCK_REPEAT_MIN     = 30             # min minutes between stuck nudges

# Recovery prescription (v5) — surfaced when in cooldown / on exit ritual.
RECOVERY_GOOD_SLEEP    = 4            # sleep score (out of 5) considered restored
RECOVERY_LATE_NIGHT_OK = 1            # >=N late blocks last 7d => prescribe a no-Claude window

# ---------------------------------------------------------------- state io

def now() -> datetime:
    return datetime.now(timezone.utc)

def iso(dt: datetime) -> str:
    return dt.isoformat(timespec="seconds")

def parse(ts: str) -> datetime:
    return datetime.fromisoformat(ts)

def default_state() -> dict:
    created = now()
    return {
        "version": 6,
        "config": {"tone": "supportive", "stuck_detection": True},
        "created_at": iso(created),
        "preview_until": iso(created + timedelta(days=PREVIEW_DAYS)),
        "blocks": [],          # [{start, end, beats, late_night}] continuous work blocks
        "sessions": [],        # legacy/manual log-session entries (still honoured)
        "checkins": [],
        "pulses": [],          # [{ts, value}] daily 1-item burnout reading
        "contract": None,      # {lockout_index?, stop_by_hour?, max_daily_hours?, ...}
        "sprint": None,        # {name, started_at, until, recovery_until, pending_cancel?}
        "projects": {},        # {path: {deep_work: bool, since: iso}}
        "cooldown": None,
        "parking_lot": [],
        "override_penalty": 0,
        "last_alerts": {},     # {alert_key: iso_ts} rate limiting
        "events": [],
        "records": {},         # all-time bests + sustainable rhythm
    }

def load_state() -> dict:
    if not STATE_FILE.exists():
        return default_state()
    try:
        state = json.loads(STATE_FILE.read_text())
    except json.JSONDecodeError:
        STATE_FILE.rename(STATE_FILE.with_suffix(".corrupt.json"))
        return default_state()
    v = state.get("version", 1)
    if v < 2:
        state.setdefault("parking_lot", [])
        if state.get("cooldown"):
            state["cooldown"].setdefault("trigger_level", 4)
            state["cooldown"].setdefault("recovery_plan", None)
    if v < 3:
        state.setdefault("blocks", [])
        state.setdefault("last_alerts", {})
    if v < 4:
        state.setdefault("records", {})
    if v < 5:
        state.setdefault("pulses", [])
        state.setdefault("contract", None)
        # Preview window: anchor to existing created_at so upgraders don't get a fresh
        # 7-day grace they didn't ask for; if their preview already lapsed, leave it.
        if "preview_until" not in state:
            try:
                created_at = parse(state.get("created_at", iso(now())))
            except Exception:
                created_at = now()
            state["preview_until"] = iso(created_at + timedelta(days=PREVIEW_DAYS))
    if v < 6:
        state.setdefault("sprint", None)
        state.setdefault("projects", {})
        # Drop legacy grind streak fields (deprecated in v4, scheduled for v5/v6 removal).
        rec = state.get("records") or {}
        for legacy_key in ("longest_streak_days_alltime", "longest_streak_at",
                           "current_streak_days"):
            rec.pop(legacy_key, None)
        state["records"] = rec
    state.setdefault("config", {"tone": "supportive"})
    state["config"].setdefault("stuck_detection", True)
    state["version"] = 6
    return state

def save_state(state: dict) -> None:
    HOME.mkdir(parents=True, exist_ok=True)
    tmp = STATE_FILE.with_suffix(".tmp")
    tmp.write_text(json.dumps(state, indent=2))
    tmp.replace(STATE_FILE)

def audit(state: dict, event_type: str, detail: str) -> None:
    state["events"].append({"ts": iso(now()), "type": event_type, "detail": detail})
    state["events"] = state["events"][-500:]

# ---------------------------------------------------------------- attention

def is_late(dt_local: datetime) -> bool:
    return dt_local.hour >= LATE_NIGHT_START or dt_local.hour < LATE_NIGHT_END

def record_beat(state: dict) -> dict:
    """Stitch this moment into the current continuous block. Returns the live block."""
    t = now()
    blocks = state["blocks"]
    if blocks and (t - parse(blocks[-1]["end"])) <= timedelta(minutes=BLOCK_GAP_MIN):
        b = blocks[-1]
        b["end"] = iso(t)
        b["beats"] = b.get("beats", 1) + 1
        b["late_night"] = b.get("late_night") or is_late(datetime.now())
    else:
        b = {"start": iso(t), "end": iso(t), "beats": 1,
             "late_night": is_late(datetime.now())}
        blocks.append(b)
    state["blocks"] = blocks[-1000:]
    return b

def block_minutes(b: dict) -> float:
    return (parse(b["end"]) - parse(b["start"])).total_seconds() / 60

# ---------------------------------------------------------------- transcripts

def parse_iso_z(ts: str) -> datetime | None:
    """Parse Claude Code transcript timestamps. Tolerates trailing Z (3.10-safe)."""
    if not isinstance(ts, str):
        return None
    try:
        if ts.endswith("Z"):
            ts = ts[:-1] + "+00:00"
        return datetime.fromisoformat(ts)
    except Exception:
        return None

def transcript_beats(cutoff: datetime) -> list[datetime]:
    """Read ~/.claude/projects/**/*.jsonl and return user-prompt timestamps >= cutoff.

    Best-effort: returns [] on any error. Skips tool-result events (those have a list
    `content`); only counts genuine user prompts. Honors lookback + file caps so a
    user with hundreds of projects doesn't pay an O(N) tax on every status call."""
    beats: list[datetime] = []
    if not TRANSCRIPTS_ROOT.exists() or not TRANSCRIPTS_ROOT.is_dir():
        return beats
    file_floor = (now() - timedelta(days=TRANSCRIPT_LOOKBACK_DAYS)).timestamp()
    files: list[Path] = []
    try:
        for proj in TRANSCRIPTS_ROOT.iterdir():
            if not proj.is_dir():
                continue
            try:
                for jsonl in proj.glob("*.jsonl"):
                    try:
                        if jsonl.stat().st_mtime >= file_floor:
                            files.append(jsonl)
                    except OSError:
                        continue
            except OSError:
                continue
    except OSError:
        return beats
    if len(files) > TRANSCRIPT_MAX_FILES:
        files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        files = files[:TRANSCRIPT_MAX_FILES]

    for jsonl in files:
        try:
            with jsonl.open("r", encoding="utf-8", errors="replace") as f:
                for line in f:
                    if '"type":"user"' not in line and '"type": "user"' not in line:
                        continue
                    try:
                        ev = json.loads(line)
                    except Exception:
                        continue
                    if ev.get("type") != "user":
                        continue
                    msg = ev.get("message") or {}
                    # Tool-result envelopes carry a list content; real prompts are str.
                    if not isinstance(msg.get("content"), str):
                        continue
                    dt = parse_iso_z(ev.get("timestamp", ""))
                    if dt is None or dt < cutoff:
                        continue
                    beats.append(dt)
        except (OSError, IOError):
            continue
    beats.sort()
    return beats

def pi_session_beats(cutoff: datetime) -> list[datetime]:
    """Read Pi coding-agent sessions and return human-prompt timestamps >= cutoff.

    Mirror of transcript_beats() for the Pi platform. Pi stores sessions at
    ~/.pi/agent/sessions/--<path>--/*.jsonl. Each line is a typed entry; genuine human
    prompts are {"type":"message","message":{"role":"user",...}}. Unlike Claude, Pi
    wraps content as a list of blocks, and auto-injects skill/template blocks as "user"
    messages too — so we count text-bearing user messages whose first text block is NOT
    an injection wrapper. Best-effort: returns [] on any error, honours the same
    lookback + file caps, and is a complete no-op when the directory is absent."""
    beats: list[datetime] = []
    if not PI_SESSIONS_ROOT.exists() or not PI_SESSIONS_ROOT.is_dir():
        return beats
    file_floor = (now() - timedelta(days=TRANSCRIPT_LOOKBACK_DAYS)).timestamp()
    files: list[Path] = []
    try:
        for proj in PI_SESSIONS_ROOT.iterdir():
            if not proj.is_dir():
                continue
            try:
                for jsonl in proj.glob("*.jsonl"):
                    try:
                        if jsonl.stat().st_mtime >= file_floor:
                            files.append(jsonl)
                    except OSError:
                        continue
            except OSError:
                continue
    except OSError:
        return beats
    if len(files) > TRANSCRIPT_MAX_FILES:
        files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        files = files[:TRANSCRIPT_MAX_FILES]

    for jsonl in files:
        try:
            with jsonl.open("r", encoding="utf-8", errors="replace") as f:
                for line in f:
                    if '"role":"user"' not in line and '"role": "user"' not in line:
                        continue
                    try:
                        ev = json.loads(line)
                    except Exception:
                        continue
                    if ev.get("type") != "message":
                        continue
                    msg_obj = ev.get("message") or {}
                    if msg_obj.get("role") != "user":
                        continue
                    # Extension/skill-injected messages carry a source; skip them.
                    if ev.get("source") or msg_obj.get("source"):
                        continue
                    content = msg_obj.get("content")
                    text = ""
                    if isinstance(content, str):
                        text = content
                    elif isinstance(content, list):
                        for blk in content:
                            if isinstance(blk, dict) and blk.get("type") == "text":
                                text = blk.get("text") or ""
                                break
                    stripped = text.lstrip()
                    if stripped.startswith(PI_INJECTION_PREFIXES):
                        continue
                    dt = parse_iso_z(ev.get("timestamp", ""))
                    if dt is None or dt < cutoff:
                        continue
                    beats.append(dt)
        except (OSError, IOError):
            continue
    beats.sort()
    return beats

def stitch_intervals(items: list[tuple[datetime, datetime, int, bool]]) -> list[dict]:
    """Merge (start, end, beats, late) tuples into blocks using BLOCK_GAP_MIN."""
    items = sorted(items)
    merged: list[list] = []
    gap = timedelta(minutes=BLOCK_GAP_MIN)
    for s, e, beats, late in items:
        if merged and s - merged[-1][1] <= gap:
            merged[-1][1] = max(merged[-1][1], e)
            merged[-1][2] += beats
            merged[-1][3] = merged[-1][3] or late
        else:
            merged.append([s, e, beats, late])
    return [{"start": iso(s), "end": iso(e), "beats": b, "late_night": l}
            for s, e, b, l in merged]

def unified_blocks(state: dict, days: int) -> list[dict]:
    """State blocks + transcript-derived beats, merged into a single timeline."""
    cutoff = now() - timedelta(days=days)
    items: list[tuple[datetime, datetime, int, bool]] = []
    for b in state.get("blocks", []):
        s, e = parse(b["start"]), parse(b["end"])
        if e < cutoff:
            continue
        items.append((s, e, int(b.get("beats", 1)), bool(b.get("late_night", False))))
    for t in transcript_beats(cutoff):
        items.append((t, t, 1, is_late(t.astimezone())))
    for t in pi_session_beats(cutoff):
        items.append((t, t, 1, is_late(t.astimezone())))
    return stitch_intervals(items)

# ---------------------------------------------------------------- records

def update_records(state: dict, blocks: list[dict], thresh: dict) -> None:
    """Track all-time longest sprint and sustainable-rhythm streak. The legacy
    grind-streak metric (longest_streak_days_alltime) was removed in v5 — it was
    rewarding the exact behaviour the tool exists to interrupt. Thresholds come
    from the resolved baseline so 'no-blowout day' tracks a personal definition,
    not the absolute defaults."""
    rec = state.setdefault("records", {})
    if blocks:
        longest = max(blocks, key=block_minutes)
        cur = round(block_minutes(longest), 1)
        if cur > rec.get("longest_block_min_alltime", 0):
            rec["longest_block_min_alltime"] = cur
            rec["longest_block_at"] = longest["end"]

    # Sustainable rhythm streak: a "good day" had work AND no block above
    # long_block_2 AND no late-night block. The metric we actually want to grow.
    by_day: dict = {}
    for b in blocks:
        by_day.setdefault(parse(b["start"]).date(), []).append(b)
    long_cap = thresh["long_block_2_min"]
    good_days = {d for d, day_blocks in by_day.items()
                 if all(block_minutes(b) <= long_cap for b in day_blocks)
                 and not any(b.get("late_night") for b in day_blocks)}
    rs, d = 0, now().date()
    while d in good_days:
        rs += 1
        d -= timedelta(days=1)
    rec["sustainable_rhythm_streak_current"] = rs
    if rs > rec.get("sustainable_rhythm_streak_alltime", 0):
        rec["sustainable_rhythm_streak_alltime"] = rs
        rec["sustainable_rhythm_streak_at"] = iso(now())

# ---------------------------------------------------------------- baseline

def percentile(values: list[float], pct: float) -> float:
    """Linear-interp percentile. Empty -> 0. pct in [0, 100]."""
    if not values:
        return 0.0
    s = sorted(values)
    if len(s) == 1:
        return float(s[0])
    k = (len(s) - 1) * pct / 100.0
    f = int(k)
    c = min(f + 1, len(s) - 1)
    return float(s[f] + (s[c] - s[f]) * (k - f))

def baseline(state: dict) -> dict:
    """Return calibrated alert thresholds — long_block_1/2 minutes and heavy_day
    hours — derived from the trailing 30 days. Falls back to absolute defaults until
    BASELINE_MIN_DAYS_ACTIVE distinct days are observed; clamps within
    BASELINE_BOUNDS so a couch-potato baseline can't disable protection and a
    marathon baseline can't remove the cap."""
    blocks = unified_blocks(state, days=BASELINE_LOOKBACK_DAYS)
    days_seen = {parse(b["start"]).date() for b in blocks}

    if len(days_seen) < BASELINE_MIN_DAYS_ACTIVE:
        return {"calibrated": False, "days_observed": len(days_seen),
                "long_block_1_min": LONG_BLOCK_1_MIN,
                "long_block_2_min": LONG_BLOCK_2_MIN,
                "heavy_day_hours":  HEAVY_DAY_HOURS}

    durations = [block_minutes(b) for b in blocks]
    daily_min: dict = {}
    for b in blocks:
        daily_min[parse(b["start"]).date()] = \
            daily_min.get(parse(b["start"]).date(), 0) + block_minutes(b)
    daily_hours = [m / 60 for m in daily_min.values()]

    def clamp_within(value: float, key: str) -> float:
        lo, hi = BASELINE_BOUNDS[key]
        return max(lo, min(hi, value))

    return {"calibrated": True, "days_observed": len(days_seen),
            "long_block_1_min": round(clamp_within(percentile(durations, 75),
                                                   "long_block_1_min")),
            "long_block_2_min": round(clamp_within(percentile(durations, 90),
                                                   "long_block_2_min")),
            "heavy_day_hours":  round(clamp_within(percentile(daily_hours, 75),
                                                   "heavy_day_hours"), 1)}

# ---------------------------------------------------------------- contract

def contract_is_stricter(field: str, new_val: float, current_val: float) -> bool:
    """True iff new_val tightens protection vs current_val for this field."""
    direction = CONTRACT_STRICT_DIR[field]
    if direction < 0:
        return new_val < current_val
    return new_val > current_val

def effective_contract(state: dict) -> dict:
    """Resolved contract values, applying any pending loosening that has matured.
    Returns {} if no contract is active. Does NOT mutate state — that happens in
    settle_contract() called from save paths."""
    c = state.get("contract")
    if not c:
        return {}
    out = {f: c[f] for f in CONTRACT_FIELDS if f in c}
    pl = c.get("pending_loosening")
    if pl and parse(pl["applies_at"]) <= now():
        out.update(pl.get("values", {}))
    return out

def settle_contract(state: dict) -> bool:
    """If a pending loosening has matured, apply it permanently. Returns True if
    state was mutated. Called from any command that saves state."""
    c = state.get("contract")
    if not c:
        return False
    pl = c.get("pending_loosening")
    if not pl:
        return False
    if parse(pl["applies_at"]) > now():
        return False
    c.update(pl.get("values", {}))
    c["last_modified"] = iso(now())
    c.pop("pending_loosening")
    audit(state, "contract_loosen_applied", json.dumps(pl.get("values", {})))
    return True

def resolved_thresholds(state: dict, cwd: str | None = None) -> dict:
    """Baseline → contract → sprint phase → deep-work-project. The single source of
    truth for thresholds. Order matters: baseline first (personal), contracts tighten
    only, sprint phase relaxes (during) or tightens (recovery), deep-work projects
    only relax block-stretch alerts when actively working in them — never the
    lockout boundary."""
    bl = baseline(state)
    out = {"long_block_1_min": bl["long_block_1_min"],
           "long_block_2_min": bl["long_block_2_min"],
           "heavy_day_hours":  bl["heavy_day_hours"],
           "lockout_index":    65,
           "stop_by_hour":     LATE_NIGHT_START,
           "max_daily_hours":  bl["heavy_day_hours"],
           "calibrated":       bl["calibrated"],
           "days_observed":    bl["days_observed"],
           "sprint_phase":     sprint_phase(state),
           "deep_work_active": is_deep_work_cwd(state, cwd)}

    # Contracts can only tighten beyond defaults.
    c = effective_contract(state)
    if "lockout_index" in c:
        out["lockout_index"] = min(out["lockout_index"], c["lockout_index"])
    if "stop_by_hour" in c:
        out["stop_by_hour"] = min(out["stop_by_hour"], c["stop_by_hour"])
    if "max_daily_hours" in c:
        out["max_daily_hours"] = min(out["max_daily_hours"], c["max_daily_hours"])
        out["heavy_day_hours"] = min(out["heavy_day_hours"], c["max_daily_hours"])

    # Sprint phase. During: relax block + heavy-day (you committed to push). Recovery:
    # tighten heavy-day and pull lockout floor in. Both clamped within absolute bounds
    # so sprint can't blow past 300-min long-block-2 or 8h heavy-day.
    if out["sprint_phase"] == "active":
        out["long_block_1_min"] = min(BASELINE_BOUNDS["long_block_1_min"][1],
                                      int(out["long_block_1_min"] * SPRINT_DURING_BLOCK_MULT))
        out["long_block_2_min"] = min(BASELINE_BOUNDS["long_block_2_min"][1],
                                      int(out["long_block_2_min"] * SPRINT_DURING_BLOCK_MULT))
        out["heavy_day_hours"] = min(BASELINE_BOUNDS["heavy_day_hours"][1],
                                     out["heavy_day_hours"] * SPRINT_DURING_HEAVY_DAY_MULT)
    elif out["sprint_phase"] == "recovery":
        out["heavy_day_hours"] = max(BASELINE_BOUNDS["heavy_day_hours"][0],
                                     out["heavy_day_hours"] * SPRINT_RECOVERY_HEAVY_MULT)
        out["lockout_index"] = min(out["lockout_index"], SPRINT_RECOVERY_LOCKOUT_IDX)

    # Deep-work project: relax block stretches only (not heavy-day, not lockout).
    if out["deep_work_active"]:
        out["long_block_1_min"] = min(BASELINE_BOUNDS["long_block_1_min"][1],
                                      int(out["long_block_1_min"] * PROJECT_DEEP_WORK_MULT))
        out["long_block_2_min"] = min(BASELINE_BOUNDS["long_block_2_min"][1],
                                      int(out["long_block_2_min"] * PROJECT_DEEP_WORK_MULT))

    return out

# ---------------------------------------------------------------- preview mode

def in_preview(state: dict) -> bool:
    pu = state.get("preview_until")
    if not pu:
        return False
    try:
        return now() < parse(pu)
    except Exception:
        return False

# ---------------------------------------------------------------- strain (v5)

def daily_focus_hours(blocks: list[dict], days: int) -> dict:
    """Return {date: focus_hours} over the trailing `days` days (UTC date keys)."""
    today = now().date()
    out = {today - timedelta(days=i): 0.0 for i in range(days)}
    for b in blocks:
        d = parse(b["start"]).date()
        if d in out:
            out[d] += block_minutes(b) / 60.0
    return out

def strain_score(state: dict) -> dict:
    """Whoop-flavoured strain: a 30-day rolling debt of (load above your typical
    daily) minus (recovery credit on light days). Distinct from the burnout index —
    index is now (am I burnt out?), strain is trajectory (am I heading there?). Both
    coexist in status/report; the SKILL.md tells Claude to surface them as different
    things so users don't average them in their head."""
    blocks = unified_blocks(state, days=STRAIN_LOOKBACK_DAYS)
    bl = baseline(state)
    # Use the user's heavy_day threshold as the "above your typical" reference. If
    # uncalibrated, use the absolute default.
    pivot_hours = bl["heavy_day_hours"]
    daily = daily_focus_hours(blocks, STRAIN_LOOKBACK_DAYS)
    debt_hours = 0.0
    for hours in daily.values():
        if hours > pivot_hours:
            debt_hours += (hours - pivot_hours)            # accumulate above-load
        elif hours == 0:
            debt_hours -= 0.5                              # full rest day = small credit
        elif hours < pivot_hours * 0.5:
            debt_hours -= 0.25                             # light day = tiny credit
    debt_hours = max(0.0, debt_hours)
    score = round(min(100.0, (debt_hours / MAX_STRAIN_DEBT_HRS) * 100.0), 1)
    band, instruction = STRAIN_DEBT_BANDS[-1][1], STRAIN_DEBT_BANDS[-1][2]
    for cap, label, advice in STRAIN_DEBT_BANDS:
        if score <= cap:
            band, instruction = label, advice
            break
    return {"score": score, "band": band, "debt_hours": round(debt_hours, 1),
            "pivot_hours": pivot_hours, "instruction": instruction,
            "lookback_days": STRAIN_LOOKBACK_DAYS}

# ---------------------------------------------------------------- sprint (v5)

def sprint_phase(state: dict) -> str:
    """One of: 'none', 'active', 'recovery', 'cancel_pending'."""
    sp = state.get("sprint")
    if not sp:
        return "none"
    n = now()
    if sp.get("pending_cancel") and parse(sp["pending_cancel"]["applies_at"]) > n:
        # Cancel queued — but during the cool-off the sprint stays active so the user
        # can finish what they committed to. Cancel takes effect after the cool-off.
        return "active" if parse(sp["until"]) > n else "recovery"
    if parse(sp["until"]) > n:
        return "active"
    if parse(sp.get("recovery_until", sp["until"])) > n:
        return "recovery"
    return "none"   # finished naturally; cleared on next save by settle_sprint

def settle_sprint(state: dict) -> bool:
    """Apply matured cancels and clear naturally-finished sprints. Returns True if
    state was mutated. Called from save paths."""
    sp = state.get("sprint")
    if not sp:
        return False
    n = now()
    pending = sp.get("pending_cancel")
    if pending and parse(pending["applies_at"]) <= n:
        audit(state, "sprint_cancel_applied", sp.get("name", ""))
        state["sprint"] = None
        return True
    if not pending and parse(sp.get("recovery_until", sp["until"])) <= n:
        audit(state, "sprint_finished", sp.get("name", ""))
        state["sprint"] = None
        return True
    return False

# ---------------------------------------------------------------- projects (v5)

def transcript_blocks_by_project(cutoff: datetime) -> dict[str, list[dict]]:
    """Group transcript-derived beats by cwd, then stitch into per-project blocks.
    Heartbeat-only blocks (no cwd) aren't bucketable here — they appear in totals
    but not in the per-project breakdown."""
    by_cwd: dict[str, list[datetime]] = {}
    if not TRANSCRIPTS_ROOT.exists() or not TRANSCRIPTS_ROOT.is_dir():
        return {}
    file_floor = (now() - timedelta(days=TRANSCRIPT_LOOKBACK_DAYS)).timestamp()
    files: list[Path] = []
    try:
        for proj in TRANSCRIPTS_ROOT.iterdir():
            if not proj.is_dir():
                continue
            try:
                for jsonl in proj.glob("*.jsonl"):
                    try:
                        if jsonl.stat().st_mtime >= file_floor:
                            files.append(jsonl)
                    except OSError:
                        continue
            except OSError:
                continue
    except OSError:
        return {}
    if len(files) > TRANSCRIPT_MAX_FILES:
        files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        files = files[:TRANSCRIPT_MAX_FILES]

    for jsonl in files:
        try:
            with jsonl.open("r", encoding="utf-8", errors="replace") as f:
                for line in f:
                    if '"type":"user"' not in line and '"type": "user"' not in line:
                        continue
                    try:
                        ev = json.loads(line)
                    except Exception:
                        continue
                    if ev.get("type") != "user":
                        continue
                    msg = ev.get("message") or {}
                    if not isinstance(msg.get("content"), str):
                        continue
                    dt = parse_iso_z(ev.get("timestamp", ""))
                    if dt is None or dt < cutoff:
                        continue
                    cwd = ev.get("cwd") or "(unknown)"
                    by_cwd.setdefault(cwd, []).append(dt)
        except (OSError, IOError):
            continue

    out: dict[str, list[dict]] = {}
    for cwd, beats in by_cwd.items():
        beats.sort()
        items = [(t, t, 1, is_late(t.astimezone())) for t in beats]
        out[cwd] = stitch_intervals(items)
    return out

def project_summary(state: dict, days: int = 7) -> list[dict]:
    """Top projects by trailing focus minutes, with deep-work flag. Best-effort."""
    cutoff = now() - timedelta(days=days)
    by_proj = transcript_blocks_by_project(cutoff)
    rows = []
    for cwd, blocks in by_proj.items():
        recent = [b for b in blocks if parse(b["end"]) >= cutoff]
        if not recent:
            continue
        total_min = sum(block_minutes(b) for b in recent)
        flag = (state.get("projects") or {}).get(cwd, {}).get("deep_work", False)
        rows.append({"path": cwd, "minutes_7d": round(total_min, 1),
                     "blocks_7d": len(recent),
                     "deep_work": flag,
                     "longest_block_min": round(max((block_minutes(b) for b in recent),
                                                   default=0), 1)})
    rows.sort(key=lambda r: r["minutes_7d"], reverse=True)
    return rows

def is_deep_work_cwd(state: dict, cwd: str | None) -> bool:
    if not cwd:
        return False
    p = (state.get("projects") or {}).get(cwd)
    return bool(p and p.get("deep_work"))

# ---------------------------------------------------------------- stuck loop (v5)

def _word_set(s: str) -> set[str]:
    return {w for w in (s.lower().split()) if len(w) >= 3}

def _jaccard(a: set, b: set) -> float:
    if not a and not b:
        return 1.0
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)

def detect_stuck_loop(prompts_recent: list[str]) -> bool:
    """Conservative spiral detector: pairwise mean Jaccard of word sets across the
    recent prompts. Designed to err toward false negatives — being wrong with a
    'looks like a loop' nudge is fine; being wrong with a lockout is not. Returns
    False below STUCK_MIN_PROMPTS so a single repeat never trips it."""
    if len(prompts_recent) < STUCK_MIN_PROMPTS:
        return False
    sets = [_word_set(p) for p in prompts_recent if p]
    if len(sets) < STUCK_MIN_PROMPTS:
        return False
    pairs = []
    for i in range(len(sets)):
        for j in range(i + 1, len(sets)):
            pairs.append(_jaccard(sets[i], sets[j]))
    if not pairs:
        return False
    return (sum(pairs) / len(pairs)) >= STUCK_JACCARD_MEAN

def recent_transcript_prompts(window_min: int) -> list[str]:
    """Best-effort: read the most recent transcript prompts within the time window.
    Returns [] on any error."""
    try:
        cutoff = now() - timedelta(minutes=window_min)
        prompts: list[tuple[datetime, str]] = []
        if not TRANSCRIPTS_ROOT.exists():
            return []
        # Only scan the few most recently modified jsonl files — recent prompts live
        # in the active session's jsonl, scanning all is overkill for a hint.
        all_files: list[Path] = []
        for proj in TRANSCRIPTS_ROOT.iterdir():
            if not proj.is_dir():
                continue
            for jsonl in proj.glob("*.jsonl"):
                try:
                    all_files.append(jsonl)
                except OSError:
                    continue
        all_files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        for jsonl in all_files[:6]:
            try:
                with jsonl.open("r", encoding="utf-8", errors="replace") as f:
                    for line in f:
                        if '"type":"user"' not in line:
                            continue
                        try:
                            ev = json.loads(line)
                        except Exception:
                            continue
                        if ev.get("type") != "user":
                            continue
                        msg = ev.get("message") or {}
                        c = msg.get("content")
                        if not isinstance(c, str):
                            continue
                        dt = parse_iso_z(ev.get("timestamp", ""))
                        if dt is None or dt < cutoff:
                            continue
                        prompts.append((dt, c))
            except (OSError, IOError):
                continue
        prompts.sort()
        return [p for _, p in prompts]
    except Exception:
        return []

# ---------------------------------------------------------------- recovery rx (v5)

def recovery_prescription(state: dict) -> dict:
    """Plain-language recovery suggestion, surfaced in cooldown_status and
    timer-elapsed messages. Derived from observable signal: last sleep score, late-
    night blocks last 7d, current strain. Intentionally simple — not medical."""
    bd_blocks = unified_blocks(state, days=7)
    late_n = sum(1 for b in bd_blocks if b.get("late_night"))
    last_sleep = None
    if state.get("checkins"):
        last_sleep = state["checkins"][-1].get("sleep")
    sl = strain_score(state)
    lines: list[str] = []
    if last_sleep is None or last_sleep < RECOVERY_GOOD_SLEEP:
        lines.append("a real night of sleep (8h target; phone out of room)")
    if late_n >= RECOVERY_LATE_NIGHT_OK:
        lines.append(f"a no-Claude window tomorrow until midday "
                     f"(you logged {late_n} late-night block{'s' if late_n != 1 else ''} "
                     "last 7 days)")
    if sl["score"] >= 60:
        lines.append("at least one fully off day in the next 72h before another sprint")
    if not lines:
        lines.append("light contact (status/checkin only) until the timer elapses, "
                     "then a fresh check-in — you may already be there")
    return {"strain": sl, "items": lines,
            "summary": "Recovery suggested: " + "; ".join(lines) + "."}

# ---------------------------------------------------------------- behaviour

def behaviour_score(state: dict) -> dict:
    """0-100 plus components, from merged blocks (+legacy sessions) over trailing 7 days.

    Sources merged: state['blocks'] (heartbeat-stitched, real-time) + Claude Code
    transcript prompts (cross-project, retroactive). Legacy `sessions` are still
    honoured as 30-min day credits. Records (longest-ever sprint, streak) are updated
    here so every score computation keeps them current."""
    cutoff = now() - timedelta(days=7)
    blocks = unified_blocks(state, days=7)
    sessions = [s for s in state["sessions"] if parse(s["ts"]) >= cutoff]
    update_records(state, unified_blocks(state, days=TRANSCRIPT_LOOKBACK_DAYS),
                   resolved_thresholds(state))

    daily_min: dict = {}
    for b in blocks:
        daily_min[parse(b["start"]).date()] = \
            daily_min.get(parse(b["start"]).date(), 0) + block_minutes(b)
    for s in sessions:                      # manual logs count as 30-min credits
        daily_min[parse(s["ts"]).date()] = daily_min.get(parse(s["ts"]).date(), 0) + 30

    avg_hours = (sum(daily_min.values()) / 60) / 7 if daily_min else 0
    longest = max((block_minutes(b) for b in blocks), default=0)
    late_n = sum(1 for b in blocks if b.get("late_night")) + \
             sum(1 for s in sessions if s.get("late_night"))

    days_active = set(daily_min)
    streak, d = 0, now().date()
    while d in days_active:
        streak += 1
        d -= timedelta(days=1)

    def clamp01(x): return max(0.0, min(1.0, x))
    volume = clamp01((avg_hours - 2) / 6) * 100          # 2h/day -> 0, 8h/day -> 100
    intensity = clamp01((longest - 60) / 180) * 100      # 1h block -> 0, 4h -> 100
    night = clamp01(late_n / 5) * 100                    # 5 late blocks/wk -> 100
    grind = clamp01((streak - 4) / 6) * 100              # 5-day streak counts, 10 max

    score = W_VOLUME * volume + W_NIGHT * night + W_STREAK * grind + W_INTENSITY * intensity
    return {"score": round(min(100, score), 1),
            "avg_hours_per_day": round(avg_hours, 2),
            "longest_block_min": round(longest),
            "late_night_blocks_7d": late_n,
            "streak_days": streak}

# ---------------------------------------------------------------- scoring

def clamp(v, lo, hi):
    return max(lo, min(hi, v))

def self_report_score(state: dict) -> float | None:
    """Prefer a fresh 5-item check-in (≤72h). If none, accept a fresh 1-item pulse
    (≤24h) at reduced weight via the index-only path. Returns None when neither
    source is fresh — behaviour-only mode (capped at L3) kicks in."""
    last_full = state["checkins"][-1] if state.get("checkins") else None
    if last_full and now() - parse(last_full["ts"]) <= timedelta(hours=72):
        raw = ((last_full["exhaustion"] - 1) * 1.25
               + (last_full["detachment"] - 1) * 1.25
               + (5 - last_full["efficacy"]) * 1.0
               + (5 - last_full["sleep"]) * 0.75
               + (last_full["pressure"] - 1) * 0.75)
        return clamp(raw * 5.0, 0, 100)

    last_pulse = state["pulses"][-1] if state.get("pulses") else None
    if last_pulse and now() - parse(last_pulse["ts"]) <= timedelta(hours=PULSE_FRESH_HOURS):
        return float(PULSE_TO_INDEX.get(int(last_pulse["value"]), 50))

    return None

def level_for(index: float) -> tuple[int, str]:
    for lvl, name, lo, hi in reversed(LEVELS):
        if index >= lo:
            return lvl, name
    return 0, "Flow"

def self_report_source(state: dict) -> str | None:
    """Which fresh source produced self_report_score, if any."""
    last_full = state["checkins"][-1] if state.get("checkins") else None
    if last_full and now() - parse(last_full["ts"]) <= timedelta(hours=72):
        return "checkin"
    last_pulse = state["pulses"][-1] if state.get("pulses") else None
    if last_pulse and now() - parse(last_pulse["ts"]) <= timedelta(hours=PULSE_FRESH_HOURS):
        return "pulse"
    return None

def compute_index(state: dict) -> dict:
    sr = self_report_score(state)
    bh = behaviour_score(state)
    src = self_report_source(state)
    if sr is None:
        index = clamp(bh["score"], 0, 64)   # behaviour alone can throttle, never lock
        basis = ("behaviour-only (no check-in/pulse fresh; capped at L3 — "
                 "log a pulse or check-in to lift the cap)")
    elif src == "pulse":
        # Pulse is a lighter self-report; weight it less than a full 5-item check-in.
        # Cap at L3 still lifts (we have *some* self-report), but blend leans behaviour.
        index = 0.4 * sr + 0.6 * bh["score"]
        index = max(index, sr * SEVERE_SELF_REPORT_FLOOR)
        basis = "blended (40% pulse, 60% behaviour; full check-in welcome)"
    else:
        index = SELF_REPORT_WEIGHT * sr + BEHAVIOUR_WEIGHT * bh["score"]
        index = max(index, sr * SEVERE_SELF_REPORT_FLOOR)
        basis = "blended (60% self-report, 40% behaviour; severe self-report floor)"
    index = clamp(index + state.get("override_penalty", 0), 0, 100)
    lvl, name = level_for(index)
    return {"index": round(index, 1), "level": lvl, "level_name": name,
            "self_report": None if sr is None else round(sr, 1),
            "self_report_source": src,
            "behaviour": bh["score"], "behaviour_detail": bh,
            "basis": basis, "override_penalty": state.get("override_penalty", 0)}

def cooldown_hours_for(index: float, level: int) -> int:
    if level >= 5:
        return int(round(36 + clamp((index - 85) / 15, 0, 1) * 36))
    return int(round(12 + clamp((index - 65) / 19, 0, 1) * 24))

# ---------------------------------------------------------------- cooldown

def start_cooldown(state: dict, index: float, level: int, reason: str) -> dict:
    hours = cooldown_hours_for(index, level)
    state["cooldown"] = {"started_at": iso(now()),
                         "ends_at": iso(now() + timedelta(hours=hours)),
                         "trigger_index": index, "trigger_level": level,
                         "reason": reason, "overrides": [], "recovery_plan": None}
    audit(state, "cooldown_start", f"L{level} index={index} hours={hours} reason={reason}")
    return state["cooldown"]

def maybe_escalate(state: dict, score: dict, source: str) -> None:
    lvl, idx = score["level"], score["index"]
    cd = state.get("cooldown")
    contract_floor = resolved_thresholds(state)["lockout_index"]   # 65 default; contract may lower
    contract_triggered = contract_floor < 65 and lvl < 4 and idx >= contract_floor
    if (lvl >= 4 or contract_triggered) and not cd:
        # Contract-triggered cooldowns label as L4 ("Lockout"): no task work, override available.
        effective_lvl = max(lvl, 4)
        reason = (f"contract: index {idx} >= committed floor {contract_floor}"
                  if contract_triggered else f"auto: L{lvl} on {source}")
        start_cooldown(state, idx, effective_lvl, reason)
    elif cd and lvl == 5 and cd.get("trigger_level", 4) < 5:
        start_cooldown(state, idx, 5, f"escalation: L4 -> L5 on {source}")

def cooldown_status(state: dict) -> dict:
    cd = state.get("cooldown")
    if not cd:
        return {"locked": False}
    remaining = parse(cd["ends_at"]) - now()
    timer_elapsed = remaining.total_seconds() <= 0
    lvl = cd.get("trigger_level", 4)
    return {"locked": True, "lock_level": lvl,
            "started_at": cd["started_at"], "ends_at": cd["ends_at"],
            "timer_elapsed": timer_elapsed,
            "remaining_human": "0h 0m" if timer_elapsed else
                f"{int(remaining.total_seconds() // 3600)}h {int(remaining.total_seconds() % 3600 // 60)}m",
            "trigger_index": cd["trigger_index"], "reason": cd["reason"],
            "override_available": lvl < 5 and len(cd.get("overrides", [])) == 0,
            "overrides_used": len(cd.get("overrides", [])),
            "exit_requires": f"timer elapsed AND fresh check-in (2h) with index <= {EXIT_INDEX_MAX}"
                             + (" AND a written recovery plan (--plan)" if lvl >= 5 else "")}

# ---------------------------------------------------------------- alerts

def alert_due(state: dict, key: str, cooldown_min: int = ALERT_REPEAT_MIN) -> bool:
    last = state["last_alerts"].get(key)
    if last and now() - parse(last) < timedelta(minutes=cooldown_min):
        return False
    state["last_alerts"][key] = iso(now())
    return True

PASS_PREFIXES = ("bg:", "burnout:")   # deliberate-act prefix: always passes the hook

def tone_of(state: dict) -> str:
    return state.get("config", {}).get("tone", "supportive")

# Two voices, one engine. Sarcastic mode is opt-in (`burnout.py tone sarcastic`)
# and deliberately softens at L5 and never touches crisis territory — wit about
# the situation, never about the person's feelings.
MSG = {
    "block90": {
        "supportive": "🧯 {mins} minutes continuous — good moment for a short break.",
        "sarcastic":  "🧯 {mins} minutes straight. The bug will still be there after "
                      "you blink. Wild concept, I know: a break.",
    },
    "block150": {
        "supportive": "🧯 You've been at this {h}h {m}m without a real gap. Strong "
                      "nudge: stand up, water, 10 minutes away. The code will keep.",
        "sarcastic":  "🧯 {h}h {m}m without a gap. At this point the chair legally "
                      "owns you. Stand up — give gravity a win.",
    },
    "heavyday": {
        "supportive": "🧯 {hours}h of focused Claude work today. Worth deciding now "
                      "when today ends.",
        "sarcastic":  "🧯 {hours}h of focused work today. Bold strategy. Have you "
                      "considered scheduling the part where you stop?",
    },
    "latenight": {
        "supportive": "🧯 Late-night session logged. These weigh heavily in your "
                      "burnout index — if this becomes a pattern, the level will climb.",
        "sarcastic":  "🧯 Ah, the late-night session — famously when humanity's best "
                      "decisions get made. Noted on your permanent record "
                      "(the burnout index).",
    },
    "throttle": {
        "supportive": "🧯 Burnout Guard: index {index} — L3 Throttle. Single-task "
                      "mode: one thing at a time, ~45-min time-box; Claude will park "
                      "the rest.",
        "sarcastic":  "🧯 Index {index} — L3 Throttle. One task. Singular. I know, "
                      "devastating. Everything else goes to the parking lot, where "
                      "ideas go to survive you.",
    },
    "lock": {
        "supportive": "🧯 Burnout Guard — L{lvl} {name} active. {remaining} remaining "
                      "(triggered at index {idx}). Task work is paused. You can still "
                      "chat, check status, or park tasks{override}. Start any message "
                      "with `bg:` to talk to Claude — that channel is ALWAYS open "
                      "(venting, status, parking tasks, the exit ritual, and anything "
                      "urgent or personal).",
        "sarcastic":  "🧯 L{lvl} {name}: {remaining} remaining. You did technically do "
                      "this to yourself (index {idx}){override}. Complaints department "
                      "is open — start any message with `bg:` and Claude will listen "
                      "to all of them. That channel always works, including for "
                      "anything actually serious.",
    },
    "timer_done": {
        "supportive": "🧯 Burnout Guard — L{lvl} cooldown timer has elapsed. Exit "
                      "ritual required: a fresh check-in scoring <= {exitmax}{plan}. "
                      "Start your message with `bg:` to run it, e.g. `bg: let's do "
                      "the exit check-in`.",
        "sarcastic":  "🧯 Timer's done — congratulations on surviving rest. One "
                      "formality left: an exit check-in scoring <= {exitmax}{plan}. "
                      "Type `bg: let's do the exit check-in` and prove it.",
    },
    "bg_open": {
        "supportive": "🧯 bg: channel open — L{lvl} protocol still applies "
                      "(conversation, status, parking, exit ritual, emergencies; "
                      "no task work).",
        "sarcastic":  "🧯 bg: channel open. Talk away — but the workbench stays "
                      "locked (L{lvl}), and no, rephrasing the task as a fun "
                      "hypothetical doesn't count.",
    },
}

def msg(state: dict, key: str, **kw) -> str:
    t = tone_of(state)
    # L5 always softens back to supportive phrasing for lock/timer messages —
    # sarcasm has a floor.
    if key in ("lock", "timer_done") and kw.get("lvl", 0) >= 5:
        t = "supportive"
    return MSG[key][t].format(**kw)

def build_console_alerts(state: dict, block: dict, score: dict, cd: dict,
                         prompt: str = "", cwd: str | None = None) -> dict:
    """Returns hook-output JSON: a block decision, a systemMessage alert, or {}.

    Thresholds resolve through baseline → contract → sprint phase → deep-work
    project (cwd-aware). During preview mode (first 7 days from install) L4/L5
    surface as warnings instead of platform-blocking. Stuck-loop detection is
    conservative: console nudge only, never throttles or locks."""
    thresh = resolved_thresholds(state, cwd=cwd)

    # Deliberate-act passthrough: conversation, exit ritual, parking, emergencies.
    if cd["locked"] and prompt.strip().lower().startswith(PASS_PREFIXES):
        lvl = cd["lock_level"]
        return {"systemMessage": msg(state, "bg_open", lvl=lvl),
                "hookSpecificOutput": {"hookEventName": "UserPromptSubmit",
                    "additionalContext": f"Burnout Guard: L{lvl} lockout active; user "
                        "opened the bg: channel. Follow the lockout protocol — "
                        "conversation/status/parking/exit ritual yes, task work no. "
                        "Crisis or distress dissolves all lockout framing."}}
    # 0) Override grace window: enforcement pauses for 60 min after an L4 override.
    grace = state["last_alerts"].get("override_grace_until")
    if cd["locked"] and grace and now() < parse(grace):
        return {"systemMessage": "🧯 Override grace active — lockout enforcement "
                                 "resumes when the 60-minute window closes."}

    # 1) Locked.
    if cd["locked"]:
        lock_lvl = cd["lock_level"]
        if cd["timer_elapsed"]:
            reason = msg(state, "timer_done", lvl=lock_lvl, exitmax=EXIT_INDEX_MAX,
                         plan=(" plus a short written recovery plan" if lock_lvl >= 5 else ""))
        else:
            override_txt = (". One logged override is available for genuine emergencies"
                            if cd["override_available"] else
                            "; no override at this level" if lock_lvl >= 5 else
                            "; the override has been used")
            reason = msg(state, "lock", lvl=lock_lvl,
                         name="Hard Lockout" if lock_lvl >= 5 else "Lockout",
                         remaining=cd["remaining_human"], idx=cd["trigger_index"],
                         override=override_txt)
        # Preview mode: soften the platform block to a console warning so first-week
        # users see what would happen without being surprised. Real enforcement
        # engages once preview_until passes.
        if in_preview(state):
            return {"systemMessage": "🧯 PREVIEW: a real lockout would fire here. "
                    + reason
                    + " Real enforcement engages after "
                    + state.get("preview_until", "") + "."}
        return {"decision": "block", "reason": reason}

    msgs = []
    mins = block_minutes(block)

    # 2) Throttle reminder (rate-limited).
    if score["level"] == 3 and alert_due(state, "throttle", THROTTLE_REMINDER_MIN):
        msgs.append(msg(state, "throttle", index=score["index"]))

    # 3) Continuous-stretch alerts (personalised).
    long2 = thresh["long_block_2_min"]
    long1 = thresh["long_block_1_min"]
    if mins >= long2 and alert_due(state, "block150"):
        msgs.append(msg(state, "block150", h=int(mins // 60), m=int(mins % 60)))
    elif mins >= long1 and alert_due(state, "block90"):
        msgs.append(msg(state, "block90", mins=int(mins)))

    # 4) Heavy-day alert (personalised; contract can pull this earlier).
    today_min = sum(block_minutes(b) for b in state["blocks"]
                    if parse(b["start"]).date() == now().date())
    if today_min >= thresh["heavy_day_hours"] * 60 and alert_due(state, "heavyday", 120):
        msgs.append(msg(state, "heavyday", hours=f"{today_min / 60:.1f}"))

    # 5) Late-night start (contract can pull stop_by_hour earlier than 23).
    local_now = datetime.now()
    stop_h = thresh["stop_by_hour"]
    if (local_now.hour >= stop_h or local_now.hour < LATE_NIGHT_END) \
       and alert_due(state, "latenight", 120):
        msgs.append(msg(state, "latenight"))

    # 6) Stuck-loop nudge (conservative, console-only, never affects index/lockout).
    if state.get("config", {}).get("stuck_detection", True):
        stuck_threshold = thresh["long_block_1_min"] * STUCK_BLOCK1_FRACTION
        if mins >= stuck_threshold and alert_due(state, "stuck", STUCK_REPEAT_MIN):
            recent = recent_transcript_prompts(STUCK_WINDOW_MIN)
            if detect_stuck_loop(recent[-8:]):
                msgs.append("🧯 Looks like a stuck loop — several near-duplicate "
                            "prompts in the last few minutes. A fresh perspective "
                            "in 10 minutes will land more than another retry now.")

    # 7) Sprint-phase context line (rate-limited; just a quiet status reminder).
    sp = thresh["sprint_phase"]
    if sp == "recovery" and alert_due(state, "sprint_recovery", 240):
        msgs.append("🧯 Post-sprint recovery window — heavy-day threshold is tight; "
                    "this is the rest you committed to.")

    if msgs:
        return {"systemMessage": " ".join(msgs)}
    return {}

# ---------------------------------------------------------------- commands

def cmd_heartbeat(args):
    """Called by Claude Code hooks on every prompt/turn. Must never crash a prompt."""
    try:
        try:
            hook_input = json.loads(sys.stdin.read()) if not sys.stdin.isatty() else {}
        except Exception:
            hook_input = {}
        state = load_state()
        settle_sprint(state)
        settle_contract(state)
        block = record_beat(state)
        score = compute_index(state)
        maybe_escalate(state, score, "heartbeat")
        cd = cooldown_status(state)
        cwd = hook_input.get("cwd") if isinstance(hook_input, dict) else None

        if args.event == "session-start":
            bd = score["behaviour_detail"]
            thresh = resolved_thresholds(state)
            ctx = (f"Burnout Guard status: index {score['index']} — "
                   f"L{score['level']} {score['level_name']}. "
                   f"{LEVEL_INSTRUCTIONS[max(score['level'], cd['lock_level'] if cd['locked'] else 0)]}")
            # Pre-session friction: surface personal-baseline summary when the past
            # week is heavier than the user's calibrated norm. Friction at the moment
            # of intent (Cold Turkey/Opal pattern) beats nag 90 minutes in.
            if thresh["calibrated"] and bd["avg_hours_per_day"] >= thresh["heavy_day_hours"]:
                ctx += (f" Heads-up: {bd['avg_hours_per_day']}h/day this week vs "
                        f"your ~{thresh['heavy_day_hours']}h personal heavy-day "
                        f"threshold — Claude should ask once whether today is meant "
                        f"to be a lighter day before diving into task work.")
            elif in_preview(state):
                ctx += (f" Preview mode active until {state.get('preview_until','')}: "
                        f"L4/L5 will surface as warnings, not platform blocks.")
            out = {"hookSpecificOutput": {"hookEventName": "SessionStart",
                                          "additionalContext": ctx}}
        elif args.event == "stop":
            out = {}                      # silent: just extends the block
        else:                             # user-prompt-submit (default)
            prompt = hook_input.get("prompt", "") if isinstance(hook_input, dict) else ""
            out = build_console_alerts(state, block, score, cd, prompt, cwd=cwd) \
                  if args.hook else {"beat": True, "score": score, "cooldown": cd}
        save_state(state)
        print(json.dumps(out))
    except Exception as e:
        # Fail open: never break the user's prompt because of us.
        print(json.dumps({}))
        print(f"burnout-guard heartbeat error: {e}", file=sys.stderr)
    sys.exit(0)

def cmd_status(args):
    state = load_state()
    settle_contract(state)
    settle_sprint(state)
    score = compute_index(state)
    cd = cooldown_status(state)
    thresh = resolved_thresholds(state)
    strain = strain_score(state)
    rx = recovery_prescription(state) if cd["locked"] else None
    if cd["locked"]:
        effective, verdict, code = max(score["level"], cd["lock_level"], 4), "LOCKED", 10
    elif score["level"] == 3:
        effective, verdict, code = 3, "THROTTLED", 5
    else:
        effective, verdict, code = score["level"], "UNLOCKED", 0
    print(json.dumps({"score": score, "effective_level": effective,
                      "effective_level_name": dict((l, n) for l, n, *_ in LEVELS)[effective],
                      "cooldown": cd, "parking_lot_size": len(state["parking_lot"]),
                      "verdict": verdict, "tone": tone_of(state),
                      "records": state.get("records", {}),
                      "thresholds": thresh,
                      "strain": strain,
                      "sprint": state.get("sprint"),
                      "sprint_phase": sprint_phase(state),
                      "contract": effective_contract(state) or None,
                      "preview_mode": in_preview(state),
                      "preview_until": state.get("preview_until"),
                      "recovery": rx,
                      "instruction": LEVEL_INSTRUCTIONS[effective]},
                     indent=2))
    sys.exit(code)

def cmd_log_session(args):
    state = load_state()
    late = is_late(datetime.now())
    state["sessions"].append({"ts": iso(now()), "late_night": late})
    state["sessions"] = state["sessions"][-1000:]
    record_beat(state)
    audit(state, "session", f"late_night={late}")
    score = compute_index(state)
    maybe_escalate(state, score, "session log")
    save_state(state)
    print(json.dumps({"logged": True, "late_night": late, "score": score,
                      "cooldown": cooldown_status(state)}, indent=2))

def cmd_checkin(args):
    state = load_state()
    for field in ("exhaustion", "detachment", "efficacy", "sleep", "pressure"):
        if not 1 <= getattr(args, field) <= 5:
            print(f"error: --{field} must be 1-5", file=sys.stderr)
            sys.exit(2)
    entry = {"ts": iso(now()), "exhaustion": args.exhaustion,
             "detachment": args.detachment, "efficacy": args.efficacy,
             "sleep": args.sleep, "pressure": args.pressure, "notes": args.notes or ""}
    state["checkins"].append(entry)
    state["checkins"] = state["checkins"][-365:]
    score = compute_index(state)
    entry["index_at_checkin"] = score["index"]
    if score["level"] <= 1:
        state["override_penalty"] = 0
        score = compute_index(state)
    audit(state, "checkin", f"index={score['index']} L{score['level']}")
    maybe_escalate(state, score, "check-in")
    save_state(state)
    print(json.dumps({"recorded": True, "score": score,
                      "cooldown": cooldown_status(state)}, indent=2))

def cmd_defer(args):
    state = load_state()
    task = (args.task or "").strip()
    if len(task) < 3:
        print("error: --task description required", file=sys.stderr)
        sys.exit(2)
    state["parking_lot"].append({"ts": iso(now()), "task": task})
    audit(state, "defer", task[:120])
    save_state(state)
    print(json.dumps({"deferred": True, "parking_lot_size": len(state["parking_lot"])},
                     indent=2))

def cmd_parked(args):
    state = load_state()
    if args.clear:
        n = len(state["parking_lot"])
        state["parking_lot"] = []
        audit(state, "parking_lot_clear", f"cleared {n}")
        save_state(state)
        print(json.dumps({"cleared": n}, indent=2))
        return
    print(json.dumps({"parking_lot": state["parking_lot"]}, indent=2))

def cmd_cooldown(args):
    state = load_state()
    if args.action == "start":
        score = compute_index(state)
        start_cooldown(state, max(score["index"], 65), max(score["level"], 4),
                       args.reason or "manual start")
        save_state(state)
        print(json.dumps({"started": True, "cooldown": cooldown_status(state)}, indent=2))
        return
    cd = cooldown_status(state)
    if not cd["locked"]:
        print(json.dumps({"cleared": False, "detail": "no active cooldown"}, indent=2))
        return
    if not cd["timer_elapsed"]:
        print(json.dumps({"cleared": False,
                          "detail": f"timer not elapsed — {cd['remaining_human']} remaining"},
                         indent=2))
        sys.exit(10)
    fresh = state["checkins"] and (now() - parse(state["checkins"][-1]["ts"]) < timedelta(hours=2))
    if not fresh:
        print(json.dumps({"cleared": False,
                          "detail": "exit check-in required (within last 2h) before clearing"},
                         indent=2))
        sys.exit(10)
    score = compute_index(state)
    if score["index"] > EXIT_INDEX_MAX:
        start_cooldown(state, score["index"], max(score["level"], 4),
                       "extension: exit check-in still too high")
        save_state(state)
        print(json.dumps({"cleared": False, "extended": True,
                          "detail": f"index {score['index']} > {EXIT_INDEX_MAX}; cooldown extended",
                          "cooldown": cooldown_status(state)}, indent=2))
        sys.exit(10)
    if cd["lock_level"] >= 5:
        plan = (args.plan or "").strip()
        if len(plan) < RECOVERY_PLAN_MIN_CHARS:
            print(json.dumps({"cleared": False,
                              "detail": f"L5 exit requires --plan >= {RECOVERY_PLAN_MIN_CHARS} chars: "
                                        "what changes this week so this doesn't recur?"},
                             indent=2))
            sys.exit(10)
        state["cooldown"]["recovery_plan"] = plan
        audit(state, "recovery_plan", plan[:200])
    audit(state, "cooldown_clear", f"exit index={score['index']}")
    state["cooldown"] = None
    save_state(state)
    out = {"cleared": True, "score": score, "parking_lot_size": len(state["parking_lot"])}
    if state["parking_lot"]:
        out["detail"] = "Parking lot has items — offer them back one at a time."
    print(json.dumps(out, indent=2))

def cmd_override(args):
    state = load_state()
    cd = state.get("cooldown")
    if not cd:
        print(json.dumps({"override": False, "detail": "no active cooldown"}, indent=2))
        return
    if cd.get("trigger_level", 4) >= 5:
        print(json.dumps({"override": False,
                          "detail": "Hard Lockout (L5): overrides are disabled by design."},
                         indent=2))
        sys.exit(10)
    if len(cd.get("overrides", [])) >= 1:
        print(json.dumps({"override": False,
                          "detail": "override already used for this cooldown"}, indent=2))
        sys.exit(10)
    if not args.reason or len(args.reason.strip()) < 15:
        print("error: --reason of at least 15 characters required (it is logged)",
              file=sys.stderr)
        sys.exit(2)
    cd["overrides"].append({"ts": iso(now()), "reason": args.reason.strip()})
    state["override_penalty"] = state.get("override_penalty", 0) + OVERRIDE_PENALTY
    # Grace window: next prompts within 60 min won't be hard-blocked by the hook.
    state["last_alerts"]["override_grace_until"] = iso(now() + timedelta(minutes=60))
    audit(state, "override", args.reason.strip())
    save_state(state)
    print(json.dumps({"override": True,
                      "detail": "One-time pass: hook enforcement pauses for 60 minutes "
                                "for THIS task, then the lockout resumes. "
                                f"+{OVERRIDE_PENALTY} penalty until next calm check-in."},
                     indent=2))

def cmd_sprint(args):
    """Declare or end a sprint. During: thresholds relax (you committed to push, the
    system stops crying wolf). After: an automatic post-recovery period with tighter
    heavy-day and a pulled-in lockout floor. Cancel queues for 7 days — the sprint
    you committed to on Sunday isn't dissolved at 11pm Wednesday."""
    state = load_state()
    settle_sprint(state)

    if args.action == "show":
        sp = state.get("sprint")
        thr = resolved_thresholds(state)
        print(json.dumps({"sprint": sp, "phase": sprint_phase(state),
                          "effective_thresholds": thr}, indent=2))
        return

    if args.action == "finish":
        sp = state.get("sprint")
        if not sp:
            print(json.dumps({"finished": False, "detail": "no active sprint"}, indent=2))
            return
        if sprint_phase(state) == "active":
            # Finishing early skips straight to recovery. The recovery window starts
            # now and lasts (work-already-done * SPRINT_RECOVERY_RATIO).
            elapsed = (now() - parse(sp["started_at"]))
            sp["until"] = iso(now())
            sp["recovery_until"] = iso(now() + elapsed * SPRINT_RECOVERY_RATIO)
            audit(state, "sprint_finish_early", sp.get("name", ""))
        save_state(state)
        print(json.dumps({"finished": True, "phase": sprint_phase(state),
                          "sprint": state.get("sprint")}, indent=2))
        return

    if args.action == "cancel":
        sp = state.get("sprint")
        if not sp:
            print(json.dumps({"cancelled": False, "detail": "no active sprint"}, indent=2))
            return
        sp["pending_cancel"] = {
            "requested_at": iso(now()),
            "applies_at": iso(now() + timedelta(days=SPRINT_CANCEL_COOLOFF_DAYS)),
        }
        audit(state, "sprint_cancel_queued", sp.get("name", ""))
        save_state(state)
        print(json.dumps({"queued": True,
                          "detail": f"cancel will apply in {SPRINT_CANCEL_COOLOFF_DAYS} days; "
                                    "until then the sprint stays active so you can finish what "
                                    "you committed to. The queue is the feature.",
                          "applies_at": sp["pending_cancel"]["applies_at"]}, indent=2))
        return

    # declare
    if state.get("sprint") and sprint_phase(state) != "none":
        print("error: a sprint is already active or in recovery; finish or cancel it first",
              file=sys.stderr)
        sys.exit(2)
    if not args.name or len(args.name.strip()) < 3:
        print("error: --name required (at least 3 chars)", file=sys.stderr)
        sys.exit(2)
    if not args.until:
        print("error: --until DATE (YYYY-MM-DD) required", file=sys.stderr)
        sys.exit(2)
    try:
        until_dt = datetime.fromisoformat(args.until).replace(tzinfo=timezone.utc)
    except Exception:
        print("error: --until must be YYYY-MM-DD", file=sys.stderr)
        sys.exit(2)
    if until_dt <= now():
        print("error: --until must be in the future", file=sys.stderr)
        sys.exit(2)
    duration_days = (until_dt - now()).days + 1
    if duration_days > SPRINT_MAX_DAYS:
        print(f"error: sprint capped at {SPRINT_MAX_DAYS} days. If the work is longer "
              f"than that, it is not a sprint, it is a project — and projects need "
              f"weekly recovery, not 'I'll rest after.'", file=sys.stderr)
        sys.exit(2)
    recovery_until = until_dt + (until_dt - now()) * SPRINT_RECOVERY_RATIO
    state["sprint"] = {
        "name": args.name.strip(),
        "started_at": iso(now()),
        "until": iso(until_dt),
        "recovery_until": iso(recovery_until),
        "rationale": (args.rationale or "").strip() or None,
    }
    audit(state, "sprint_declare",
          f"{args.name.strip()} until {args.until} (recovery until {iso(recovery_until)})")
    save_state(state)
    print(json.dumps({"declared": True, "sprint": state["sprint"],
                      "phase": "active",
                      "effective_thresholds": resolved_thresholds(state)}, indent=2))

def cmd_project(args):
    """Mark a project (cwd path) as deep-work — long-block thresholds widen by
    PROJECT_DEEP_WORK_MULT when actively in that cwd. Lockout boundary unaffected."""
    state = load_state()
    if args.action == "list":
        ps = project_summary(state, days=7)
        flagged = (state.get("projects") or {})
        print(json.dumps({"top_by_focus_7d": ps, "flagged": flagged}, indent=2))
        return
    if not args.path:
        print("error: --path required", file=sys.stderr)
        sys.exit(2)
    path = args.path.strip()
    projects = state.setdefault("projects", {})
    if args.action == "mark":
        projects[path] = {"deep_work": bool(args.deep_work),
                          "since": iso(now())}
        audit(state, "project_mark", f"{path} deep_work={bool(args.deep_work)}")
    elif args.action == "unmark":
        projects.pop(path, None)
        audit(state, "project_unmark", path)
    save_state(state)
    print(json.dumps({"projects": projects}, indent=2))

def cmd_pulse(args):
    """Daily 1-item burnout reading. Cheap to log every day; smooths self-report."""
    state = load_state()
    if not 1 <= args.value <= 5:
        print("error: value must be 1-5 (1=fresh, 5=fumes)", file=sys.stderr)
        sys.exit(2)
    settle_contract(state)
    state["pulses"].append({"ts": iso(now()), "value": int(args.value),
                            "note": (args.note or "").strip() or None})
    state["pulses"] = state["pulses"][-365:]
    audit(state, "pulse", str(args.value))
    score = compute_index(state)
    maybe_escalate(state, score, "pulse")
    save_state(state)
    print(json.dumps({"recorded": True, "value": int(args.value),
                      "score": score, "cooldown": cooldown_status(state)}, indent=2))

def _contract_normalize(state: dict, candidate: dict) -> tuple[dict, dict]:
    """Split a candidate contract update into (apply_now, queue_loosen) by comparing
    each field against the current effective value. Stricter changes apply
    immediately; looser changes wait CONTRACT_LOOSEN_COOLOFF_DAYS."""
    eff = effective_contract(state)
    apply_now: dict = {}
    queue_loosen: dict = {}
    for f, v in candidate.items():
        baseline_val = eff.get(f, CONTRACT_DEFAULTS[f])
        if contract_is_stricter(f, v, baseline_val):
            apply_now[f] = v
        elif v == baseline_val:
            continue
        else:
            queue_loosen[f] = v
    return apply_now, queue_loosen

def cmd_contract(args):
    """Pre-commitment device. Tightening is instant; loosening waits 7 days."""
    state = load_state()
    settle_contract(state)

    if args.action == "show":
        eff = effective_contract(state)
        print(json.dumps({"contract": state.get("contract"),
                          "effective": eff,
                          "thresholds": resolved_thresholds(state)}, indent=2))
        return

    if args.action == "clear":
        cur = state.get("contract") or {}
        # If the contract was making things stricter, clearing it is a loosening —
        # apply the same 7-day cooling-off. Otherwise (already-empty contract)
        # this is a no-op.
        if not cur or all(f not in cur for f in CONTRACT_FIELDS):
            state["contract"] = None
            save_state(state)
            print(json.dumps({"cleared": True, "detail": "no active contract"}, indent=2))
            return
        cur["pending_loosening"] = {
            "values": {f: CONTRACT_DEFAULTS[f] for f in CONTRACT_FIELDS if f in cur},
            "requested_at": iso(now()),
            "applies_at": iso(now() + timedelta(days=CONTRACT_LOOSEN_COOLOFF_DAYS)),
            "kind": "clear",
        }
        audit(state, "contract_clear_queued", "")
        save_state(state)
        print(json.dumps({"queued": True,
                          "detail": f"clear scheduled for {cur['pending_loosening']['applies_at']} "
                                    f"({CONTRACT_LOOSEN_COOLOFF_DAYS}-day cooling-off; "
                                    "stricter pre-commitments shouldn't be undone in the moment)",
                          "contract": state["contract"]}, indent=2))
        return

    # set
    candidate: dict = {}
    if args.lockout_index is not None:
        if not 40 <= args.lockout_index <= 65:
            print("error: --lockout-index must be 40-65 (40=L2, 65=L4 default)", file=sys.stderr)
            sys.exit(2)
        candidate["lockout_index"] = int(args.lockout_index)
    if args.stop_by is not None:
        if not 16 <= args.stop_by <= 23:
            print("error: --stop-by must be hour 16-23 (24h clock)", file=sys.stderr)
            sys.exit(2)
        candidate["stop_by_hour"] = int(args.stop_by)
    if args.max_daily_hours is not None:
        if not 1.0 <= args.max_daily_hours <= 8.0:
            print("error: --max-daily-hours must be 1.0-8.0", file=sys.stderr)
            sys.exit(2)
        candidate["max_daily_hours"] = float(args.max_daily_hours)
    if not candidate:
        print("error: nothing to set; pass at least one of "
              "--lockout-index / --stop-by / --max-daily-hours", file=sys.stderr)
        sys.exit(2)

    apply_now, queue_loosen = _contract_normalize(state, candidate)
    c = state.get("contract") or {"set_at": iso(now())}
    if apply_now:
        c.update(apply_now)
        c["last_modified"] = iso(now())
        audit(state, "contract_tighten", json.dumps(apply_now))
    if queue_loosen:
        c["pending_loosening"] = {
            "values": queue_loosen,
            "requested_at": iso(now()),
            "applies_at": iso(now() + timedelta(days=CONTRACT_LOOSEN_COOLOFF_DAYS)),
            "kind": "loosen",
        }
        audit(state, "contract_loosen_queued", json.dumps(queue_loosen))
    state["contract"] = c
    save_state(state)
    print(json.dumps({"applied_now": apply_now,
                      "queued_loosen": queue_loosen,
                      "queued_until": c.get("pending_loosening", {}).get("applies_at"),
                      "effective": effective_contract(state),
                      "thresholds": resolved_thresholds(state)}, indent=2))

def cmd_history(args):
    state = load_state()
    print(json.dumps({"recent_checkins": state["checkins"][-args.n:],
                      "recent_blocks": state["blocks"][-args.n:],
                      "recent_events": state["events"][-args.n:],
                      "parking_lot": state["parking_lot"]}, indent=2))

SPARK_BARS = "▁▂▃▄▅▆▇█"

def sparkline(values: list[float]) -> str:
    if not values:
        return ""
    hi = max(values)
    if hi <= 0:
        return SPARK_BARS[0] * len(values)
    out = []
    for v in values:
        if v <= 0:
            out.append(" ")
        else:
            out.append(SPARK_BARS[min(len(SPARK_BARS) - 1,
                                      int(v / hi * (len(SPARK_BARS) - 1) + 0.5))])
    return "".join(out)

def daily_minutes(blocks: list[dict], days: int) -> list[tuple[str, float]]:
    """Returns [(YYYY-MM-DD, minutes)] for the last `days` days, oldest first."""
    today = now().astimezone().date()
    bucket: dict = {today - timedelta(days=i): 0.0 for i in range(days)}
    for b in blocks:
        s, e = parse(b["start"]).astimezone(), parse(b["end"]).astimezone()
        cur = s
        while cur < e:
            day_end = datetime.combine(cur.date(), datetime.min.time(),
                                       tzinfo=cur.tzinfo) + timedelta(days=1)
            chunk_end = min(day_end, e)
            mins = (chunk_end - cur).total_seconds() / 60
            if cur.date() in bucket:
                bucket[cur.date()] += mins
            cur = chunk_end
    return [(d.isoformat(), round(m, 1))
            for d, m in sorted(bucket.items())]

HEATMAP_SHADES = " ░▒▓█"

def heatmap_7x24(blocks: list[dict]) -> list[str]:
    """7×24 grid (Mon..Sun × hour-of-day) of focused minutes. Local time."""
    grid = [[0.0] * 24 for _ in range(7)]
    for b in blocks:
        s = parse(b["start"]).astimezone()
        e = parse(b["end"]).astimezone()
        cur = s.replace(minute=0, second=0, microsecond=0)
        while cur < e:
            nxt = cur + timedelta(hours=1)
            mins = (min(nxt, e) - max(cur, s)).total_seconds() / 60
            if mins > 0:
                grid[cur.weekday()][cur.hour] += mins
            cur = nxt
    flat = [v for row in grid for v in row]
    hi = max(flat) if flat else 0
    if hi <= 0:
        return ["  (no recorded activity in window)"]
    days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    header = "      " + "".join(f"{h:>3}" for h in (0, 3, 6, 9, 12, 15, 18, 21))
    lines = [header]
    for i, row in enumerate(grid):
        cells = ""
        for v in row:
            if v <= 0:
                cells += HEATMAP_SHADES[0]
            else:
                idx = min(len(HEATMAP_SHADES) - 1,
                          1 + int((v / hi) * (len(HEATMAP_SHADES) - 2) + 0.5))
                cells += HEATMAP_SHADES[idx]
        lines.append(f"  {days[i]} {cells}")
    lines.append(f"  legend: {HEATMAP_SHADES} (none → ~{int(hi)} min/cell)")
    return lines

def cmd_report(args):
    state = load_state()
    score = compute_index(state)
    cd = cooldown_status(state)
    bd = score["behaviour_detail"]
    cutoff = now() - timedelta(days=14)
    checkins = [c for c in state["checkins"] if parse(c["ts"]) >= cutoff]
    lockouts = [e for e in state["events"]
                if e["type"] == "cooldown_start" and parse(e["ts"]) >= cutoff]
    blocks_14 = unified_blocks(state, days=14)
    rec = state.get("records", {})

    daily = daily_minutes(blocks_14, 14)
    spark = sparkline([m for _, m in daily])
    peak_min = max((m for _, m in daily), default=0)

    pulses_14 = [p for p in state.get("pulses", []) if parse(p["ts"]) >= cutoff]
    thresh = resolved_thresholds(state)
    eff_contract = effective_contract(state)
    strain = strain_score(state)
    proj_top = project_summary(state, days=7)[:5]
    sp = state.get("sprint")

    cal_line = (f"**Calibration:** personal baseline ({thresh['days_observed']} days observed) — "
                f"long-block alerts at {thresh['long_block_1_min']}/{thresh['long_block_2_min']} min, "
                f"heavy day at {thresh['heavy_day_hours']}h, "
                f"late-night from {thresh['stop_by_hour']:02d}:00."
                if thresh["calibrated"] else
                f"**Calibration:** still warming up ({thresh['days_observed']} of "
                f"{BASELINE_MIN_DAYS_ACTIVE} days observed) — using absolute defaults.")

    lines = [
        "# Burnout Guard — 14-day report",
        f"\n**Current index:** {score['index']} — **L{score['level']} {score['level_name']}**",
        f"**Basis:** {score['basis']}",
        f"**Lockout:** {'ACTIVE (L' + str(cd['lock_level']) + ') until ' + cd['ends_at'] if cd['locked'] else 'none'}",
        f"{cal_line}",
        f"**Preview mode:** {'active until ' + state.get('preview_until','') if in_preview(state) else 'off'}",
        f"\n## Attention (trailing 7 days)",
        f"- Average focused hours/day: {bd['avg_hours_per_day']}",
        f"- Longest continuous stretch: {bd['longest_block_min']} min",
        f"- Late-night blocks: {bd['late_night_blocks_7d']}",
        f"- Behaviour score: {bd['score']}/100",
        f"\n## Daily focus (14d, mins/day, peak ~{int(peak_min)})",
        f"  {daily[0][0]} {spark} {daily[-1][0]}",
        f"\n## Hour-of-day × day-of-week (14d, local time)",
        *heatmap_7x24(blocks_14),
        f"\n## Records",
        f"- Longest sprint ever: {rec.get('longest_block_min_alltime', 0)} min"
        + (f" (on {rec['longest_block_at']})" if rec.get('longest_block_at') else ""),
        f"- **Sustainable rhythm streak (the one to grow):** "
        f"{rec.get('sustainable_rhythm_streak_current', 0)} day(s) current, "
        f"{rec.get('sustainable_rhythm_streak_alltime', 0)} day(s) all-time — "
        "days with work AND no over-long block AND no late-night block",
        f"\n## Self-report",
        f"- Daily pulses (14d): {len(pulses_14)}"
        + (f", latest: {pulses_14[-1]['value']}/5 ({pulses_14[-1]['ts']})" if pulses_14 else ""),
        f"- Full check-ins (14d): {len(checkins)}",
    ]
    if checkins:
        last = checkins[-1]
        lines.append(f"- Latest check-in ({last['ts']}): exhaustion {last['exhaustion']}/5, "
                     f"detachment {last['detachment']}/5, efficacy {last['efficacy']}/5, "
                     f"sleep {last['sleep']}/5, pressure {last['pressure']}/5")
    lines.append(f"\n## Strain (30-day debt model)")
    lines.append(f"- {strain['band']} — {strain['score']}/100 "
                 f"(debt {strain['debt_hours']}h vs {strain['pivot_hours']}h/day pivot)")
    lines.append(f"- {strain['instruction']}")

    if sp:
        lines.append(f"\n## Sprint")
        lines.append(f"- {sp.get('name', 'unnamed')} — phase: **{sprint_phase(state)}** "
                     f"(until {sp.get('until','?')}, recovery until "
                     f"{sp.get('recovery_until','?')})")
        if sp.get("rationale"):
            lines.append(f"- rationale: {sp['rationale']}")
        if sp.get("pending_cancel"):
            lines.append(f"- cancel queued, applies at {sp['pending_cancel']['applies_at']}")

    if proj_top:
        lines.append(f"\n## By project (top 5, last 7 days)")
        for p in proj_top:
            short = p["path"].split("/")[-1] or p["path"]
            mark = " [deep-work]" if p["deep_work"] else ""
            lines.append(f"- {short}{mark} — {p['minutes_7d']} min, "
                         f"{p['blocks_7d']} block(s), longest {p['longest_block_min']} min")

    if eff_contract:
        lines.append(f"\n## Contract (pre-commitments)")
        for f in CONTRACT_FIELDS:
            if f in eff_contract:
                lines.append(f"- {f}: {eff_contract[f]} (default {CONTRACT_DEFAULTS[f]})")
        pl = (state.get("contract") or {}).get("pending_loosening")
        if pl:
            lines.append(f"- pending loosening applies at {pl['applies_at']}: "
                         f"{json.dumps(pl.get('values', {}))}")

    if cd["locked"]:
        rx = recovery_prescription(state)
        lines.append(f"\n## Recovery prescription")
        lines.append(f"- {rx['summary']}")
    lines += [f"\n## Enforcement\n- Lockouts triggered (14d): {len(lockouts)}",
              f"- Parking lot: {len(state['parking_lot'])} item(s)",
              f"- Override penalty in effect: +{state.get('override_penalty', 0)}",
              f"\n## Audit\n- Events logged: {len(state['events'])}"]
    if len(lockouts) >= 2:
        lines.append("\n> Two or more lockouts in 14 days. The pattern, not the timer, is "
                     "the signal — consider a conversation with a GP or occupational health.")
    # Persist any updates update_records made via behaviour_score.
    save_state(state)
    print("\n".join(lines))

def cmd_tone(args):
    state = load_state()
    if args.mode == "show":
        print(json.dumps({"tone": tone_of(state)}, indent=2))
        return
    state.setdefault("config", {})["tone"] = args.mode
    audit(state, "tone", args.mode)
    save_state(state)
    samples = {k: MSG[k][args.mode if args.mode in MSG[k] else "supportive"]
               for k in ("block90", "lock")}
    print(json.dumps({"tone": args.mode,
                      "detail": "Applies to console alerts and lockout notices. "
                                "Sarcasm softens automatically at L5 and never "
                                "applies to crisis or distress — wit about the "
                                "situation, never about the person.",
                      "sample": samples}, indent=2))

# ---------------------------------------------------------------- hook mgmt

HOOK_MARKER = "burnout.py heartbeat"

def hook_entries(script: str) -> dict:
    return {
        "UserPromptSubmit": [{"hooks": [{"type": "command",
            "command": f"python3 {script} heartbeat --hook"}]}],
        "SessionStart": [{"hooks": [{"type": "command",
            "command": f"python3 {script} heartbeat --hook --event session-start"}]}],
        "Stop": [{"hooks": [{"type": "command",
            "command": f"python3 {script} heartbeat --hook --event stop"}]}],
    }

def cmd_hook(args):
    script = str(Path(__file__).resolve())
    settings_path = CLAUDE_SETTINGS
    settings = {}
    if settings_path.exists():
        try:
            settings = json.loads(settings_path.read_text())
        except json.JSONDecodeError:
            print(f"error: {settings_path} is not valid JSON — fix it first", file=sys.stderr)
            sys.exit(2)

    hooks = settings.get("hooks", {})
    installed = any(HOOK_MARKER in json.dumps(v) for v in hooks.values())

    if args.action == "status":
        print(json.dumps({"settings_path": str(settings_path),
                          "installed": installed, "script": script}, indent=2))
        return

    if args.action == "uninstall":
        for event in list(hooks):
            hooks[event] = [m for m in hooks[event]
                            if HOOK_MARKER not in json.dumps(m)]
            if not hooks[event]:
                del hooks[event]
        settings["hooks"] = hooks
        settings_path.write_text(json.dumps(settings, indent=2))
        print(json.dumps({"uninstalled": True}, indent=2))
        return

    # install
    if settings_path.exists():
        backup = settings_path.with_suffix(f".json.bak-{now().strftime('%Y%m%d%H%M%S')}")
        backup.write_text(settings_path.read_text())
    if installed:
        cmd_hook(argparse.Namespace(action="uninstall"))   # refresh paths
        settings = json.loads(settings_path.read_text()) if settings_path.exists() else {}
        hooks = settings.get("hooks", {})
    for event, matchers in hook_entries(script).items():
        hooks.setdefault(event, []).extend(matchers)
    settings["hooks"] = hooks
    settings_path.parent.mkdir(parents=True, exist_ok=True)
    settings_path.write_text(json.dumps(settings, indent=2))
    print(json.dumps({"installed": True, "settings_path": str(settings_path),
                      "events": list(hook_entries(script)),
                      "detail": "Restart Claude Code (or /hooks to verify). "
                                "Prompts now heartbeat; L4/L5 hard-block; console "
                                "alerts on long stretches, heavy days, late nights."},
                     indent=2))

# ---------------------------------------------------------------- main

def main():
    p = argparse.ArgumentParser(prog="burnout.py", description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("status").set_defaults(fn=cmd_status)
    sub.add_parser("log-session").set_defaults(fn=cmd_log_session)

    hb = sub.add_parser("heartbeat")
    hb.add_argument("--hook", action="store_true",
                    help="emit Claude Code hook JSON (block/systemMessage)")
    hb.add_argument("--event", choices=["prompt", "session-start", "stop"],
                    default="prompt")
    hb.set_defaults(fn=cmd_heartbeat)

    hk = sub.add_parser("hook")
    hk.add_argument("action", choices=["install", "uninstall", "status"])
    hk.set_defaults(fn=cmd_hook)

    ci = sub.add_parser("checkin")
    for f, h in [("exhaustion", "1=fresh 5=fumes"), ("detachment", "1=engaged 5=checked out"),
                 ("efficacy", "1=useless 5=on top of it"), ("sleep", "1=terrible 5=great"),
                 ("pressure", "1=light 5=crushing")]:
        ci.add_argument(f"--{f}", type=int, required=True, help=h)
    ci.add_argument("--notes", type=str, default="")
    ci.set_defaults(fn=cmd_checkin)

    df = sub.add_parser("defer")
    df.add_argument("--task", type=str, required=True)
    df.set_defaults(fn=cmd_defer)

    pk = sub.add_parser("parked")
    pk.add_argument("--clear", action="store_true")
    pk.set_defaults(fn=cmd_parked)

    cd = sub.add_parser("cooldown")
    cd.add_argument("action", choices=["start", "clear"])
    cd.add_argument("--reason", type=str, default="")
    cd.add_argument("--plan", type=str, default="")
    cd.set_defaults(fn=cmd_cooldown)

    ov = sub.add_parser("override")
    ov.add_argument("--reason", type=str, required=True)
    ov.set_defaults(fn=cmd_override)

    tn = sub.add_parser("tone")
    tn.add_argument("mode", choices=["supportive", "sarcastic", "show"])
    tn.set_defaults(fn=cmd_tone)

    pl = sub.add_parser("pulse",
                        help="daily 1-item burnout reading (1=fresh, 5=fumes)")
    pl.add_argument("value", type=int, help="1-5")
    pl.add_argument("--note", type=str, default="")
    pl.set_defaults(fn=cmd_pulse)

    sp = sub.add_parser("sprint",
                        help="declare a sprint (relaxed during, auto-recovery after); "
                             "cancel queues 7 days")
    sp.add_argument("action", choices=["declare", "show", "finish", "cancel"])
    sp.add_argument("--name", type=str, default=None)
    sp.add_argument("--until", type=str, default=None,
                    help="YYYY-MM-DD (last day of sprint, inclusive)")
    sp.add_argument("--rationale", type=str, default=None,
                    help="optional: what you're shipping and why now")
    sp.set_defaults(fn=cmd_sprint)

    pr = sub.add_parser("project",
                        help="mark/unmark/list projects; deep-work flag widens block "
                             "thresholds when active in that cwd")
    pr.add_argument("action", choices=["mark", "unmark", "list"])
    pr.add_argument("--path", type=str, default=None)
    pr.add_argument("--deep-work", action="store_true")
    pr.set_defaults(fn=cmd_project)

    co = sub.add_parser("contract",
                        help="pre-commitment device — tighten now, loosening waits 7 days")
    co.add_argument("action", choices=["set", "show", "clear"])
    co.add_argument("--lockout-index", type=int, default=None,
                    help="trigger lockout at this index (40-65; default 65)")
    co.add_argument("--stop-by", type=int, default=None,
                    help="late-night threshold hour, 24h clock (16-23; default 23)")
    co.add_argument("--max-daily-hours", type=float, default=None,
                    help="heavy-day alert threshold in hours (1.0-8.0; default 4)")
    co.set_defaults(fn=cmd_contract)

    hi = sub.add_parser("history")
    hi.add_argument("-n", type=int, default=10)
    hi.set_defaults(fn=cmd_history)

    sub.add_parser("report").set_defaults(fn=cmd_report)

    args = p.parse_args()
    args.fn(args)

if __name__ == "__main__":
    main()
